### ISSUE TITLE
[Elastic Agent] Enable HTTP endpoint configuration for Elastic Agent

### ISSUE THREAD

**Issue by nimarezainia** [elastic/elastic-agent#107]
**Describe the enhancement:**

Enable the HTTP Endpoint for Elastic Agent  to bring us to parity. This should be done on a "per policy basis"

**Describe a specific use case for the enhancement or feature:**

as per what is already available for filebeat

**Comment by jlind23** [comment]
@ph shouldn't we close this one and rather rely on the liveness probe one?

**Comment by jlind23** [comment]
@nimarezainia is this one still required? Haven't seen traction on this for a while.

**Comment by cmacknz** [comment]
For standalone this has been implemented for a while, and https://github.com/elastic/elastic-agent/pull/4586 made it reloadable from Fleet. Closing.

**Comment by zez3** [comment]
@cmacknz or @nimarezainia what would then be the recommend way to LB healthcheck managed Agents?

**Comment by cmacknz** [comment]
In 8.15.0 there will be a `/liveness` endpoint that is enabled whenever `agent.monitoring.http.enabled: true` is set in the policy, available where that same server is configured to be exposed. By default it returns a 200 OK status as long agent's internal main loop is responsive and can process configuration changes. It can be configured to also monitor the component states to return an error if anything is degraded or failed.

There's no documentation to point at yet because it isn't released.

**Comment by nimarezainia** [comment]
fyi: @kilfoyle

**Comment by nimarezainia** [comment]
@zez3 you can preview the Fleet changes  here: https://github.com/elastic/kibana/pull/180922
