### ISSUE TITLE
Liveness endpoint behaviour when unable to check in with fleet server

### ISSUE THREAD

**Issue by michel-laterman** [elastic/elastic-agent#1157]
As a fix to the issue in https://github.com/elastic/elastic-agent/issues/1148 made in https://github.com/elastic/elastic-agent/pull/1152. The elastic-agent will no longer report a degraded state if the checkin to fleet-server fails.

This degraded state reporting was used by the liveness endpoint to ensure that the agent reported a 200 status when healthy.
The original changes were added as part of https://github.com/elastic/elastic-agent/pull/569.

We need to decide what the liveness endpoint should be reporting and how that interacts with what the agent report to fleet.

**Comment by cmacknz** [comment]
I think the issue with the original implementation was the possibility for the agent to check in and report a degraded state because of the inability to check in, which is a bit of a paradoxical situation given that you have to check in to do it.

To me it makes the most sense to align what the agent's local liveness endpoint does with the equivalent of what Fleet considers for the agent offline state.

We released this functionality in v8.4.0 so we shouldn't break it by not reporting when the agent cannot connect to Fleet server. I think we should address this in v8.5.0 by:

1) Reporting an error from the agent's liveness endpoint using the same threshold and logic that Fleet itself uses to determine this.  The Fleet logic for offline is defined here: https://github.com/elastic/kibana/blob/342e7a17839dc78a4b29d7770eaad3138a8bddb8/x-pack/plugins/fleet/common/services/agent_status.ts#L24-L42

2) Only reporting this offline state via the liveness endpoint, and never reporting to Fleet. Hopefully we can accomplish this by filtering a new offline state from the state reporter or something similar.

@michel-laterman thoughts on this?

**Comment by blakerouse** [comment]
Yes I think what we need here is 2 different statuses. The first is a local status, so what is my status as the Elastic Agent is local to the machine. The second is the status that is reported to Fleet Server.

When `elastic-agent status` is called or the liveness probe is used the fact that communication with Fleet Server is failing is important information.

**Comment by michel-laterman** [comment]
@cmacknz, that sounds good it should also appear in `elastic-agent status` as that would be an easy indicator for customers

**Comment by jlind23** [comment]
@michel-laterman would you be able to take this one on your plate as it seems you understand the whole picture here?

**Comment by michel-laterman** [comment]
Would this need to be backported to 8.5? The changes we're making for 8.6 means a fix for 8.5 is a completely separate fix.

**Comment by jlind23** [comment]
@michel-laterman as previous fix landed in 8.5 I think it would be great to have a fix backported to 8.5 too.
@cmacknz thoughts?

**Comment by cmacknz** [comment]
Yes lets backport to 8.5 so as not to break anything in that release.
