### ISSUE TITLE
Upgrade occasionally failing on Windows

### ISSUE THREAD

**Issue by michalpristas** [elastic/elastic-agent#1187]
Agent is experience some weird behavior on Upgrade.

It downloads artifacts just fine and verifies them
it does all the things necessary but after Upgrade handler is done no symlink in root directory is created (the old one cease to exist and new one is not there)

there's `elastic-agent.exe.prev` and `elastic-agent.exe.old`
not sure where `.old` comes from.

seems like only windows machines are affected

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1522652/190093708-e6e1c5fc-2e7c-4bb3-9667-7d621abaf5ee.png">

<img width="466" alt="image" src="https://user-images.githubusercontent.com/1522652/190093766-50c73c50-3925-46b6-b1b9-fb2f3207ee8f.png">

Reported for `8.3.2 -> 8.3.3` upgrade

**Comment by jlind23** [comment]
We do not have enough informations to reproduce, let's close it for now until this problem occurs again.

**Comment by michalpristas** [comment]
problem occured again

**Comment by man715** [comment]
This is regularly happening to my Windows machines as well. Are there any logs generated during the upgrade process that we can look through to see what may be causing the issue? This happens when I upgrade using the Fleet.

**Comment by pchila** [comment]
Tried to reproduce the issue for 2 days straight. The closest I got was not having the link updated during an 8.6.2 -> 8.7.0-SNAPSHOT upgrade but even that wasn't reproducible.
I and @michalpristas tried writing unit tests for both the `SafeFileRotate`  and `changeSymlink` functions invoked during the upgrade process but we still didn't manage to trigger the behavior described in the issue.

One interesting tool to use if this happens again is [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) so that we can filter the system calls during the upgrade and see if there's something strange happening when moving the elastic-agent link to the new version (we tried using it in our tests but since we didn't mange to reproduce the issue we didn't get anything useful out of that run).

**Comment by jlind23** [comment]
@pchila thanks for investigating. Let's close this as not reproducible for now. 
@man715 What is the version you are running? Do you still observe this behaviour with the latest release?

**Comment by cmacknz** [comment]
@michalpristas is this a duplicate of https://github.com/elastic/elastic-agent/issues/2645 or a separate problem?

**Comment by michalpristas** [comment]
closing, at first i thought this is the issue i'm seeing, after investigation it turned out to be different problem
