### ISSUE TITLE
[Agent] Setting Tags at enrollment and installation 

### ISSUE THREAD

**Issue by mohsen0** [elastic/elastic-agent#149]
Ability to set tags during installation and enrolment agent 
so that different identical deployments of service can be differentiated in the dataset

The specific use case is described in: https://discuss.elastic.co/t/fleet-managed-elastic-agent-environment-deployment-name-custom-field/282565/6

```
sudo ./elastic-agent install -f --url=https://<feet manager>:443 --enrollment-token=<token> --tag=staging01 
```
or in case, the agent is already installed via package manager
```
elastic-agent enroll -f --url=https://<feet manager>:443 --enrollment-token=<token> --tag=staging01 
```

**Comment by jlind23** [comment]
@nimarezainia Should we also support kubernetes label here?

**Comment by jlind23** [comment]
@nimarezainia any feedback on my last comment?

**Comment by nimarezainia** [comment]
> kubernetes label

sorry missed that. labels are KV pairs. Here we are just attaching a tag to the agent. I am not opposed to adding more labels but want to (a) avoid feature scope creep here, (b) rather approach what is needed for kubernetes in a holistic way so it can be shown in fleet as well.

**Comment by ph** [comment]
@narph We have a field in the agent model called `user_provided_metadata`, IIRC the field is populated at enrollment in the fleet api, but the elastic agent doesn't always send an empty map.

https://github.com/elastic/fleet-server/blob/main/model/schema.json#L400-L404

**Comment by jlind23** [comment]
@narph any update to share on the design document you are working on?

**Comment by narph** [comment]
I was working on a proposal doc but I think I can summarize my findings in this comment. 

The proposal above also contains overwriting the agent name by specifying the `agent_name` flag during enrollment/installation. Any reason we are not tackling that together with the tagging @jlind23 , @nimarezainia ?

**Tags field definition** 

https://www.elastic.co/guide/en/ecs/current/ecs-base.html#field-tags

Since `tags` are defined in the ecs schema I think they should follow the format:
```
tags:
 dashed_name: tags
 description: List of keywords used to tag each event.
 example: '["production", "env2"]'
 flat_name: tags
 ignore_above: 1024
 level: core
 name: tags
 normalize:
 - array
 short: List of keywords used to tag each event.
 type: keyword
```

Just a clarification here, we previously talked about the `tags` having a key/value pair format but that should be reserved for `labels` instead.

**Implementation options**

1. Reuse existing fields/functionality:

@ph  has pointed there are several options we can reuse for this field like `user_provided_metadata`  [ fleet-server/schema.json at main · elastic/fleet-server (github.com)](https://github.com/elastic/fleet-server/blob/main/model/schema.json#L400-L404), there is also `local_metadata` but based on the naming of the field, `user_provided_metadata` could be more appropriate.

Although `user_provided_metadata` can already be set during agent enroll we should still add `-tags` flag but map the existing field instead, ex:
```
elastic-agent enroll --url=https://<fleet server> --enrollment-token=<token> --tags 'linux-arm,SF-datacenter'

then map:
 "user_provided_metadata": {
      "tags": '["linux-arm", "SF-datacenter"]'
}
```

I am not seeing this field written to anywhere further
[fleet-server/handleEnroll.go at main · elastic/fleet-server (github.com)](https://github.com/elastic/fleet-server/blob/main/cmd/fleet/handleEnroll.go#L256) so the fleet UI team can use it as well  to display/update the tag values.

This implementation does have a downside that  `user_provided_metadata` is not ecs compliant and we might have user discoverability issues.

2. Add `tags` option and reuse/add the tag ecs field: 

```
elastic-agent enroll --url=https://<fleet server> --enrollment-token=<token> --tags 'linux-arm,SF-datacenter'

then map:

     "tags": '["linux-arm", "SF-datacenter"]'

```

Add `–-tags` flag and `tags` property to the enroll response to fleet ([fleet-server/schema.go at c19f455df83ba0ffd18b139fd6524e0597eb1943 · elastic/fleet-server (github.com)](https://github.com/elastic/fleet-server/blob/c19f455df83ba0ffd18b139fd6524e0597eb1943/cmd/fleet/schema.go#L58)), expand [fleet-server/schema.json at main · elastic/fleet-server (github.com)](https://github.com/elastic/fleet-server/blob/main/model/schema.json) to include tags, Fleet UI team could use the ecs `tags` field.

**Other thoughts**

In general `tags` can be too free form, for example `production` is not a great tag value in the structured ecs world as we have https://www.elastic.co/guide/en/ecs/current/ecs-service.html#field-service-environment.
Should we consider additional flags or some form of discovery for this specific information? In general I wonder whether we have too much information loss by opening this up so widely on the tags.

cc @ruflin , @joshdover

**Comment by ruflin** [comment]
I would start simple and only implement tags to get started. For the ECS part, my understanding is that the data is stored in a system index which is not queried directly by the user. The key part is that the user can write queries in ECS format so if we don't store it in ECS, a translation must happen. For tags, I can foresee that in the UI that there is special block that proposes which tags can be filtered on.

One other discussion I remember but couldn't find the conclusion: Can a user in the Fleet UI / API overwrite these tags? For example, a user enrolls an Elastic Agent with the tag `foo` and now a user in the Fleet UI removes this tag but adds `bar` instead?

**Comment by joshdover** [comment]
> I would start simple and only implement tags to get started. For the ECS part, my understanding is that the data is stored in a system index which is not queried directly by the user. The key part is that the user can write queries in ECS format so if we don't store it in ECS, a translation must happen.

@kpollich this is something we'll need to consider. We'd want the search bar on the agents page to use ECS field name even if the agent documents store the field by another name. We should be able to manipulate the KQL `kuery` to do this, I know of prior art elsewhere in Kibana if we need to copy it.

Alternatively, I wonder if we want to consider making the agent query bar ECS-compliant as a separate enhancement.

> One other discussion I remember but couldn't find the conclusion: Can a user in the Fleet UI / API overwrite these tags? For example, a user enrolls an Elastic Agent with the tag `foo` and now a user in the Fleet UI removes this tag but adds `bar` instead?

This was proposed as a phase 2 for this feature in the design document. If these tags are ever to be appended to data ingested by Agents, we'll need to consider how to make Fleet Server send down tag updates.

**Comment by ruflin** [comment]
> If these tags are ever to be appended to data ingested by Agents, we'll need to consider how to make Fleet Server send down tag updates.

Why is that? Does the agent need to know about its own tags? ++ on delaying this conversations if in the first iteration we don't offer edits anyway in Fleet. One of the reasons I brought it up initially was that the decision might impact the data model.

**Comment by joshdover** [comment]
> Why is that? Does the agent need to know about its own tags? ++ on delaying this conversations if in the first iteration we don't offer edits anyway in Fleet. One of the reasons I brought it up initially was that the decision might impact the data model.

Only if we ever want to add these tags to the data being ingested, which I have not heard a request for at this time. Agree we can defer on this.

**Comment by jlind23** [comment]
After discussing with PH, this is the path we want to take:
- We should be compliant with ECS
- We should rather use labels instead of tags as it will provide key/value pairs

Using labels it will close the gap with Kubernetes and docker integration and it will also give more flexibility to the UI filters.


Tags can be added afterwards if needed. We can also think about it this way:
- If we have a label called "tag" it can be split and added into ECS tags.
```
Label {
"tag":"A,B,C"
}
will become
Tag {
"A",
"B",
"C"
```

**Comment by narph** [comment]
@jlind23 , @ph  so to confirm here the workflow would be:

user enrolls/installs agent:

```
elastic-agent enroll --url https://<fleet server> --enrollment-token <token> --label os linux-arm --label cloud.region SF-datacenter --label tag test 
```

then map:
```json
 "labels": {
    "os": "linux-arm",
    "cloud.region": "SF-datacenter" 
},
"tags": ["test"]
```

It might be worthwhile to model this more explicitly in the CLI invocation:

```
elastic-agent enroll --url https://<fleet server> --enrollment-token <token> --label os linux-arm --label cloud.region SF-datacenter --tag test  --tag frontend
```

```json
"labels": {
  "os": "linux-arm",
  "cloud.region": "SF-datacenter" 
},
"tags": ["test", "frontend"]
```

The fleet UI could then also separate `tags` and `labels` more distinctly. 


Another question popped up, should we support certain known valid ECS labels as first class fields?

```
elastic-agent enroll --url https://<fleet server> --enrollment-token <token> --label costfactor 2 --label cloud.region SF-datacenter --label tag test 
```

```json
 "cloud" { "region": "SF-datacenter" },
 "labels": {
    "costfactor": "2",
},
"tags": ["test"]
```

That way we can give even more meaning to the fields? Suppose we can do that later and just start with labels tags for now

**Comment by ph** [comment]
@narph I think you bring a pretty good point concerning the other ecs first class fields and maybe we indeed bring too much magic here. sorry @jlind23.

There are actually two needs:

1. I am using k8s or docker and I have a label/value structure.
2. I want to use ECS fields.


For 1, we can use what you are proposing:

```
elastic-agent enroll --url https://<fleet server> --enrollment-token <token> --label os linux-arm --label cloud.region SF-datacenter --label tag test  --label tags hello
````

This would generate the following data on the agent:
```yaml
"labels": {
    "os": "linux-arm",
    "cloud.region": "SF-datacenter" 
    "tags": ["test", "hello"]
},
```

For 2, now if I want to add tags to the agent I would do 

```
elastic-agent enroll --url https://<fleet server> --enrollment-token <token> --label os linux-arm --label cloud.region SF-datacenter --tags test  --tags hello
```

This would generate the following data on the agent:

```yaml
"labels": {
    "os": "linux-arm",
    "cloud.region": "SF-datacenter" 
},
"tags": ["test", "hello"]
```

Now we can add an easy button but remove any unwanted magic.

```
elastic-agent enroll --url https://<fleet server> --enrollment-token <token> --label os linux-arm --label cloud.region SF-datacenter --label tag test  --label tags hello --populate-ecs-from-labels
```

Would result in something like this:
```yaml
"labels": {
    "os": "linux-arm",
    "cloud.region": "SF-datacenter" 
    "tags": ["test", "hello"]
},
"tags": ["test", "hello"]
```
The agent should probably tell the user about the magic.

```
Mapping
`labels.tags` => `tags`.
```

This has the following benefits:

- It separates the two features, we can prioritize label or tagging.  @nimarezainia 
- Backward compatible.
- Leverage k8s fields when asked.
- Remove any magics from the user.


The above allow supporting both labels and ecs tags.

## Questions should we use an `ecs` prefix for the cli arguments

- Should we make it clear we are referencing ecs values?

```
--ecs.tags ABC --ecs.tags BCD
--ecs.labels hello world --ecs.labels abc dce
```

- What appends if a values has space in the labels?
- What is the interface for k8s cli when dealing with the label, we should align on the syntax.

**Comment by ph** [comment]
@ruflin  as mentioned by @joshdover https://github.com/elastic/elastic-agent/issues/149#issuecomment-1096552298

I haven't seen a request for adding all the label/tags data to every data ingested by the agent, I fear that would cause a log of headache between what a user set in the integration vs what a user set at enrollment time. They may not be the same person. We could at least add the information to the logs or metrics of the Agent.

**Comment by jlind23** [comment]
@narph can we focus on Labels for now?

**Comment by ph** [comment]
@ruflin  I would like your opinion on prefixing `--ecs.*`, for me, I like it because it is explicit, It doesn't mean a user can override all the fields but at least it link with something `concrete`

**Comment by ruflin** [comment]
I think we are in the process of making something simple complicated. What is the core problem we are trying to solve here? The one I'm focusing on is having a very simple way to filter agents on. This is like filtering Github issues based on labels (in ECS tags). There can be 0-n tags for an Elastic Agent and in the agent list page I expect these to be shown beside each Elastic Agent in the UI.

ECS labels are more complicate because these are key/value pairs and a user has to write a query. Lots of meta data about each Elastic Agent we already have, like platform, os etc. and without needing the user to add anything, we can filter on. Supporting labels also adds the question on which fields should go into ECS and which ones under `labels`? Labels is much more powerful but I would argue also more complex.

The initial proposal from @narph is simple: `--tags='linux-arm,SF-datacenter'`. This is what I would start with an see later on, if we really need labels.

For the prefix: What is the benefit of exposing this to the user? Having an `ecs.tags` prefix first makes typing it harder but also exposes and abbreviation to the user they might not even know what it is. So no, I would not expose it to a user as ECS is an implementation detail. 

I do not understand how we are mixing k8s into the conversation here. If there are k8s/docker labels on the container the Elastic Agent is in, this is meta data about Elastic Agent that the user should never have to add manually. It falls into the same category like os or platform.

**Comment by narph** [comment]
created issue for doc changes https://github.com/elastic/observability-docs/issues/1819

**Comment by narph** [comment]
also update mapping in `elasticsearch` repo https://github.com/elastic/elasticsearch/pull/86298
