### ISSUE TITLE
CometD filebeat input is not working with elastic-agent

### ISSUE THREAD

**Issue by kush-elastic** [elastic/elastic-agent#1684]
While developing a new integration using cometd input, we are facing an issue in data collection. Data is not being collected and the elastic-agent is not acknowledging cometd input.

To debug more into it, we tried collecting data using cometd input with a standalone elastic-agent, but the data collection is still not happing. However, cometd input is working properly for the beats repo, so we tried to debug more into the elastic-agent repository and found that in the [filebeat.yml](https://github.com/elastic/elastic-agent/blob/main/internal/spec/filebeat.yml#L24) file, the cometd is not registered but other inputs are registered. So it seems like the issue is in the elastic-agent filebeat.yml file. cometd needs to be added in the filebeat.yml file.

**Comment by cmacknz** [comment]
You likely need to add cometd to the list of input types that agent associates with Filebeat, so that the agent knows to start a Filebeat process configured with a cometd input when an integration with a cometd input is installed.

On the main branch, this is done in https://github.com/elastic/elastic-agent/blob/d34020750b06a1d9073d2d35ae20a1e7c162385d/internal/spec/filebeat.yml#L24-L32

However we are changing the syntax for this soon, if you wait a few days we will be merging the v2 specification format to main which looks like:

https://github.com/elastic/elastic-agent/blob/fc3eba3501a0695a477a46331293331873bb850c/specs/filebeat.spec.yml#L44-L55

**Comment by milan-elastic** [comment]
@cmacknz Do we have any update on this? If you can provide more information on when we can expect to get this change roll out then that would be great!

**Comment by cmacknz** [comment]
@elastic/obs-service-integrations are you the current owner of the Salesforce cometd input in Filebeat? I think this issue has been forgotten about.

**Comment by lalit-satapathy** [comment]
@milan-elastic, it seems like, we need to add CometD in filebeat [spec](https://github.com/elastic/elastic-agent/blob/main/specs/filebeat.spec.yml). Please go ahead create a PR.

**Comment by milan-elastic** [comment]
Sure @lalit-satapathy , we'll raise one PR to add CometD in filebeat spec.

**Comment by milan-elastic** [comment]
@cmacknz Is it possible to backport this fix to older versions(v8.5.0) as well? So customers can take benefit of this fix without upgrading their elastic stack.

**Comment by cmacknz** [comment]
> Is it possible to backport this fix to older versions(v8.5.0)

We don't plan on releasing any further 8.5.x or earlier releases so backporting this now would not help users with those versions.

**Comment by kush-elastic** [comment]
Thanks for the confirmation. we are closing this as it's Done.
