### ISSUE TITLE
V2: Agent sending input and output configurations multiple times.

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1738]
This was originally discovered by the APM server team, see https://github.com/elastic/apm-server/pull/9544#issuecomment-1316473137 and https://github.com/elastic/apm-server/pull/9544#issuecomment-1316536618

We should not be sending configurations multiple times. We should additionally consider sending the policy revision with each unit configuration to make detecting repeated configurations more easily.

**Comment by cmacknz** [comment]
@fearful-symmetry any ideas what might be happening here? Have you observed this with the other Beats or is this specific to APM server?

**Comment by fearful-symmetry** [comment]
I think I might have noticed something similar to this? I ran into an issue with the shipper yesterday where I was getting two output configs, despite only having one configured. I just added a variable to check if we're getting a shipper config after we've already initialized. 

I'm not sure if I've noticed this in beats, but I'm also not sure I'd notice unless I explicitly looked for it, since beats is fairly idempotent, and arbitrary components can be reloaded without anything falling over.

I'm also not sure how this could be originating in beats either; there's nothing in the beats V2 client that tries to loop over configs or reload multiple times.

**Comment by fearful-symmetry** [comment]
Alright, verified that this is happening with the shipper. Around 30-50% of the time, We get `UnitModified` events for all of the existing units almost instantaneously, and the configs themselves (along with the expected state) appear identical.

**Comment by cmacknz** [comment]
Thanks, this is definitely a bug we should fix to avoid clients from having to work around this constantly. I assigned it to you @fearful-symmetry in the current sprint, the problem is definitely in the agent itself.

**Comment by fearful-symmetry** [comment]
Okay, narrowing in on the issue here @cmacknz 

In order for the V2 client code to send a `UnitUpdate`, it needs to detect either a change in the expected state of the unit (healthy, starting, stopped, etc), a change in the log level, or a change in the config. That logic [is here](https://github.com/elastic/elastic-agent-client/blob/bc376a4e0f9f7677b30770c69dd6c80437924e91/pkg/client/unit.go#L253). That last condition is the one that's getting triggered incorrectly.

However, in order to trigger an update from a changed config, the V2 client libraries will look for two things: That the config index (set by the elastic-agent server) is incremented, and that the configs don't match. In the case of the incorrect update, the index _is_ incremented, but the config is apparently identical. The issue seems to be the `u.config != cfg` block, which just compares the two struct pointers with a `!=` block. I'm not sure how go behaves when you use comparison operators on a pointer to a struct, but I assume it's not what we want.

I can put in a PR to fix the comparison issue, but that doesn't solve the problem of why the elastic-agent server is incrementing the config index when nothing has changed. It's possible that this is expected behavior, as the client will look for a config index _and_ a config change.

**Comment by fearful-symmetry** [comment]
Fix here: https://github.com/elastic/elastic-agent-client/pull/47

**Comment by cmacknz** [comment]
We still need to update:

- [ ] Elastic agent, both to update the client version and use `proto.Equal` in https://github.com/elastic/elastic-agent/blob/67021cfc1b66136e42a1570c559f5da4f11f68fe/pkg/component/runtime/state.go#L123-L127
- [ ] Beats, we need to update to the latest client.

**Comment by cmacknz** [comment]
Thanks.

- [ ] We also need to bump the elastic-agent-client version in fleet-server.

**Comment by cmacknz** [comment]
- [ ] And we need to update the client version in the shipper.

It would additional be good to confirm this bug is actually fixed as part of one of these client updates. The shipper might be a good candidate for that.

**Comment by cmacknz** [comment]
@fearful-symmetry verified this, no further reports. Closing.
