### ISSUE TITLE
[macOS] Installing on Ventura breaks on permissions error if Full Disk Access is not granted to installer/terminal

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#2103]
For confirmed bugs, please report:
- Version: 8.5.x, 8.6.x, 8.7.x, main
- 8.4 and lower are not affected
- Operating System: macOS 13 Ventura
- Steps to Reproduce:
1. Start a terminal application that does not have full disk access granted
2. Run the regular installation script: `sudo ./elastic-agent install --url=https://my-fleet:8220 --enrollment-token=XXXX`
3. Get error:
`Error: failed to fix permissions: chown /Library/Elastic/Agent/data/elastic-agent-c13f91/elastic-agent.app: operation not permitted`

This is not reproducible on earlier versions of macOS or on earlier versions of Elastic Agent. It only occurs with Agent 8.5+ on macOS 13 Ventura.

In 8.5 we changed how agent is package to include a `.app` file so that Full Disk Access could be granted to it for OSQuery and other integrations. This is likely related.

### Investigation from @ricardoungureanu

> here is what is happening: once `elastic-agent.app` is copied to `/Library/Elastic/Agent`, macOS enforces that modifications on the bundle can only be made by processes signed by Elastic. Even though the installer is our process and it should be allowed to modify the bundle, macOS denies it from doing so.
> Because the installer is a command line utility, tccd checks actually for the responsible pid (true parent) if it has rights to modify our bundle.
> As elastic-agent  installer is ran from the Terminal, the final codesignature check will be between Terminal.app and agent, which obviously will fail
> This should be the rootcause of Agent’s installation problem.
> ```
> tccd: [com.apple.TCC:access] AttributionChain: responsible={TCCDProcess: identifier=com.apple.Terminal, pid=19332, auid=501, euid=501, responsible_path=/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal, binary_path=/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal}, accessing={TCCDProcess: identifier=co.elastic.elastic-agent, pid=44565, auid=501, euid=0, binary_path=/Library/Elastic/Agent/data/elastic-agent-b79a5d/elastic-agent.app/Contents/MacOS/elastic-agent}, requesting={TCCDProcess: identifier=com.apple.sandboxd, pid=376, auid=0, euid=0, binary_path=/usr/libexec/sandboxd}
> ```
> More about this new changed was presented (briefly) in [this video from 4:32](https://developer.apple.com/videos/play/wwdc2022/10096/?time=272).
> From my testing I’ve noticed some inconsistencies between what they described and various scenarios that I’ve tested, so it’s possible that there are still some bugs in their implementation that might get fixed in future releases.

### Potential solutions

1. Skip changing the permissions on this file on macOS 13+ and rely on the OS's Gatekeeper to protect this file.
	- Pros: lowest effort
	- Cons: users that have gatekeeper disabled (need to check if this is actually possible) will not be as protected as they were before
2. Create the .app bundle in a temp directory and fix it's permissions before copying to the final destination
	- Pros: low effort
	- Cons: not actually sure if this will work, could break again in the future
3. Ship a proper installer package for Agent on macOS, signed by Elastic.
	- Pros: probably a better long-term solution
	- Cons: more work, breaking change for how we support installing Agent on macOS

We have the ability to get consultation from Apple through our developer contract, if needed. This may be worth doing to avoid this breaking again if Apple makes further changes.

### Workaround

Ensure that the application (eg. Terminal, or a custom package) used to install Agent has Full Disk Access before running `sudo ./elastic-agent install`

#### Related issue

There was a similar, more flaky issue that was noticed in some cases, but we haven't had luck reproducing consistently. This has a slightly different error message, but may have the same underlying cause:
1. Install Elastic Agent on a fresh host:
	```
	sudo ./elastic-agent install --url=https://my-fleet:8220 --enrollment-token=XXXX
	```
5. Try to install again (w/o uninstalling) using `-f` flag
	```
	sudo ./elastic-agent install --url=https://my-fleet:8220 --enrollment-token=XXXX -f
	```
6. Fails with error:

```
Error: failed to remove installation directory (/Library/Elastic/Agent): unlinkat /Library/Elastic/Agent/data/elastic-agent-b79a5d/elastic-agent.app/Contents/MacOS/elastic-agent: operation not permitted
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.6/fleet-troubleshooting.html
```

**Comment by prachigupta-qasource** [comment]
Hi @joshdover,

We have tried to reproduce this issue with the steps https://github.com/elastic/elastic-agent/issues/2103#issue-1534533826 on the latest **8.7.0 SNAPSHOT**  and **8.6.0 release build** on Kibana **Staging** and **Cloud** environment and found that the issue is **not reproducible**.

**Below are the observations:**

- `Elastic Agent` is `installed again` on `Mac Monterey OS` on using the `-f` flag and `no error` is shown with `8.5.3`, `8.6.0` and `8.7.0` agent versions.

**Screenshots:**

- **8.7.0 SNAPSHOT Kibana version (Both the agents enrolled is `without or with` `-f` flag is 8.7.0):**

![image](https://user-images.githubusercontent.com/97870262/212853746-e8d51ddc-0a90-4d74-80a3-85228f7484ec.png)

![image](https://user-images.githubusercontent.com/97870262/212853938-4c8464bc-a4af-4193-a2db-d9c60118f7b1.png)

- **8.6.0 Kibana version (First agent enrolled is 8.5.3 and Second agent enrolled with `-f` flag is 8.6.0 ):**

![image](https://user-images.githubusercontent.com/97870262/212878787-4c8d544e-cd38-4728-b9b4-76e905191249.png)

![image](https://user-images.githubusercontent.com/97870262/212878961-90a6c67a-9d9f-48fe-a25e-59a1f33142fa.png)

**Build details:**

```
Version: 8.7.0 SNAPSHOT
Build: 59793	
Commit: 832a128e2aae7d3a61a6df48779fe03126b30308
```

Please let us know if we are missing anything so we can try with your steps.

Thanks!

**Comment by joshdover** [comment]
Thanks, I will try again. I reproduced this a few times already, on macOS 12.6.2 (M1). We also have at least one customer reporting this same problem, maybe there's some precondition we haven't figured out yet.

**Comment by joshdover** [comment]
I wonder if it only happens if you try to force install over the same exact build, producing an error due to trying to remove the `data/elastic-agent-b79a5d/elastic-agent.app/Contents/MacOS/elastic-agent` file.

**Comment by joshdover** [comment]
I think I have figured out how to reproduce this. You have to wait between the initial installation and the next one with the `-f` flag. Note I reproduced this on macOS 12.6.2 (21G320) with an M1 Macbook, using both the x86_64 and aarch64 builds of the official 8.6.0 version.

1. Uninstall any existing agent to be sure you don't have anything already: `sudo elastic-agent uninstall`
2. Run the download and install commands from the UI:
```
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.6.0-darwin-x86_64.tar.gz   10:57:23
tar xzvf elastic-agent-8.6.0-darwin-x86_64.tar.gz
cd elastic-agent-8.6.0-darwin-x86_64
sudo ./elastic-agent install --url=https://XXXX.fleet.europe-west1.gcp.cloud.es.io:443 --enrollment-token=XXX
```
3. **Wait at least 1 minute**
4. Run the last command again, adding `-f`:
```
sudo ./elastic-agent install --url=https://XXXX.fleet.europe-west1.gcp.cloud.es.io:443 --enrollment-token=XXX -f
```
5. Get this error:
```
Error: failed to remove installation directory (/Library/Elastic/Agent): unlinkat /Library/Elastic/Agent/data/elastic-agent-b79a5d/elastic-agent.app/Contents/MacOS/elastic-agent: operation not permitted
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.6/fleet-troubleshooting.html
```
6. If you try to uninstall agent, now it's gone!
```
$ sudo elastic-agent uninstall
sudo: elastic-agent: command not found
```
7. Here's the remaining files in the `/Library/Elastic/Agent` directory after running the `-f` install that failed:
```
$ sudo tree /Library/Elastic/Agent/
/Library/Elastic/Agent/
└── data
    └── elastic-agent-b79a5d
        └── elastic-agent.app
            └── Contents
                └── MacOS
                    └── elastic-agent

6 directories, 1 file
```

**Comment by joshdover** [comment]
The QA team is having trouble reproducing this on macOS VMs. We'll need to have an agent developer verify this locally on their mac. If someone else is able to reproduce this, this is concerning from a QA perspective that we can't catch this type of issue. We'll need to discuss ways to mitigate this, though maybe determining the root cause will help uncover why.

Since we haven't many reports of this issue yet, I think it's ok to wait until this is picked up in Sprint 8. If we get more reports we can raise the priority of this.

**Comment by joshdover** [comment]
@WiegerElastic @aarju Is it possible that this issue could be triggered by some kind of protection of Elastic Agent we have installed on our corporate machines?

**Comment by joshdover** [comment]
Taking a closer look at some customer-provided logs, there seems to be a similar but possibly separate issue that errors out with a different message:

```
/postinstall: Error: failed to fix permissions: chown /Library/Elastic/Agent/data/elastic-agent-c13f91/elastic-agent.app: operation not permitted
```

This has been noticed on fresh installations on macOS 13 Ventura only.

**Comment by brunerd** [comment]
Back in November I thought the `operation not permitted` that I was seeing was related to the new App Management features of Ventura ([Slack thread](https://elastic.slack.com/archives/C03BCNS84RF/p1667408721864679)) and maybe it _still is_ but at the time I didn't realize `-f` was a potential cause of the issue! So FYI for Elastic's deployments via Jamf I am not using this option (I had gotten used to using it because older Endgame installers would balk at new OSes without `-f`)

**Comment by joshdover** [comment]
We've confirmed this happens on Ventura only with 8.5+ builds when Full Disk Access is not granted to the application that runs the installation command. This could be either a Terminal or any custom package that a user has built to distribute Agent.

You can reproduce this by:
- Use a Mac with macOS 13 Ventura
- Starting a terminal application that does not have full disk access granted
- Run the regular installation script - it does not need to have `-f`.

I was able to reproduce this on a personal machine without any issue.

For now, the guidance would be to ensure that whatever is used to deploy Elastic Agent has FDA. I will update the issue accordingly. However, we probably need to provide a better solution and ensure this case is covered in testing.

**Comment by joshdover** [comment]
@amolnater-qasource @prachigupta-qasource are you able to reproduce this on the mac machines you have access to? I'm curious how FDA interacts with a mac we only have ssh access to.

**Comment by amolnater-qasource** [comment]
Hi @joshdover

We have attempted to reproduce this issue on latest 8.7 SNAPSHOT kibana environment, however we are still not able to reproduce this issue at our end.

**Observations:**
- We installed Endpoint integration to the agent policy.
- Full Disk Access is not provided on this VM.
- When we run agent install command, agent gets installed. 
- However agent remains Unhealthy and many error logs are observed under Agent logs tab.

**Screenshots:**
![2](https://user-images.githubusercontent.com/77374876/216265665-77c5b1de-c428-4938-9a1c-5faefcacbf0b.JPG)
![3](https://user-images.githubusercontent.com/77374876/216265675-afe2be78-4037-4831-8902-39822d7bc0d5.JPG)

**Build details:**
BUILD: 60311
COMMIT: ef00463019c0ebce609070d25cee6eed59a33909

**Logs:**
[elastic-agent-diagnostics-2023-02-02T08-15-15Z-00.zip](https://github.com/elastic/elastic-agent/files/10566687/elastic-agent-diagnostics-2023-02-02T08-15-15Z-00.zip)

Please let us know if we are missing anything here.

Thanks

**Comment by joshdover** [comment]
@amolnater-qasource how do you check if you have Full Disk Access granted? I'm not even sure it's possible _not_ to have FDA when logging into a macOS VM via ssh. I believe FDA is only applied to `.app` programs, which ssh is not.

In other words, this may only be reproducible when install Agent via a GUI terminal (this might be probably an oversimplification). Can you try using VNC to log into the VM: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-mac-instance-gui-access/

**Comment by amolnater-qasource** [comment]
Hi @joshdover 

We have attempted to reproduce this issue on 8.5.3, 8.6.1 released-production and 8.7.0 SNAPSHOT environments, however the issue is still not reproducible.

**MAC:**
- Amazon EC2- macOS Ventura 13.0
- No Profiles are configured on this VM.

**VM Screenshots:**
![6](https://user-images.githubusercontent.com/77374876/216592227-f2a914bf-6308-4d0c-a2e5-752cad87bfaf.JPG)
![10](https://user-images.githubusercontent.com/77374876/216592234-ca4f964c-d234-49b1-ac15-2838f3f786a7.JPG)

**Steps followed:**
1. We took VNC access to the MAC-VM.
2. Installed mac agent to the agent policy having System and Endpoint integrations.
3. Agents installed successfully.
4. Installed mac agent using `-f` flag and it also installed successfully.
5. Logs are available for all the installed agents.

**Screenshots:**
![7](https://user-images.githubusercontent.com/77374876/216592752-368d088a-0475-4443-8991-aa435d790842.JPG)
![8](https://user-images.githubusercontent.com/77374876/216592756-b4b7be13-3bae-41e1-80c2-6fd38efd5704.JPG)
![9](https://user-images.githubusercontent.com/77374876/216592749-f7b87f42-4698-4635-bc76-6d26340fe0d2.JPG)

Please let us know if anything else is required from our end.
Thanks!

**Comment by joshdover** [comment]
@cmacknz @nimarezainia should we add a known issue to the 8.6 and 8.5 release notes?

**Comment by joshdover** [comment]
@amolnater-qasource is it possible to upgrade macOS on that VM to the latest Ventura release? We have some reports that some of the App Management features in Ventura that cause this changed behavior in later releases of Ventura.

**Comment by aarju** [comment]
Have we tested the scenario where Agent is already installed with 8.5 or older on a MacOS system that is running macOS 12.X, then the user upgrades the MacOS to Ventura and then we try to upgrade the agent to 8.7?

This is the scenario I'm curious about:
1. Create a VM running MacOS 12.X
1. Install Agent with Elastic Defend 8.5 or older
1. Upgrade the VM to 13.2
1. Use fleet to upgrade the agent to 8.7

**Comment by nimarezainia** [comment]
> @cmacknz @nimarezainia should we add a known issue to the 8.6 and 8.5 release notes?

@dedemorton and @karenzone (sorry not sure whom to forward this to) Could we add this to the past release-notes? We can craft the verbiage if required.

**Comment by joshdover** [comment]
I have updated the issue with additional context + some potential solutions. @cmacknz @blakerouse please review. If we need to talk with Apple first, we should start that soon.

**Comment by cmacknz** [comment]
> Skip changing the permissions on this file on macOS 13+ and rely on the OS's Gatekeeper to protect this file.
> Pros: lowest effort
> Cons: users that have gatekeeper disabled (need to check if this is actually possible) will not be as protected as they were before

It appears it is possible to disable GateKeeper, there is an entire page dedicated to explaining how to do it: https://disable-gatekeeper.github.io/. It does require that you have root access.

In an unmodified agent, I need to be root to even look at the contents of the installation directory and I need to be root to execute the `elastic-agent command`.
```sh
❯ sudo ls -la /Library/Elastic/Agent/data/elastic-agent-b8553c
total 8
drwxr-x---   7 root  wheel   224 Feb 10 15:43 .
drwxr-x---   5 root  wheel   160 Feb 10 15:43 ..
drwxr-x---  47 root  wheel  1504 Feb 10 15:43 components
-rwxr-x---   1 root  wheel   227 Feb 10 15:43 elastic-agent
drwxr-x---   3 root  wheel    96 Feb 10 15:43 elastic-agent.app
drwx------   3 root  wheel    96 Feb 10 15:43 logs
drwxr-x---   6 root  wheel   192 Feb 10 15:43 run
❯ elastic-agent status
zsh: permission denied: elastic-agent
```

To test what happens when we don't fix the permissions, I made the following change to the agent to remove the logic to fix the permissions and then installed it on my MacOS Monterey machine:

```diff
diff --git a/internal/pkg/agent/install/perms_unix.go b/internal/pkg/agent/install/perms_unix.go
index 53f5ddaa1..6c4a53c4d 100644
--- a/internal/pkg/agent/install/perms_unix.go
+++ b/internal/pkg/agent/install/perms_unix.go
@@ -8,9 +8,7 @@
 package install

 import (
-       "errors"
        "io/fs"
-       "os"
        "path/filepath"

        "github.com/elastic/elastic-agent/internal/pkg/agent/application/paths"
@@ -23,17 +21,6 @@ func fixPermissions() error {

 func recursiveRootPermissions(path string) error {
        return filepath.Walk(path, func(name string, info fs.FileInfo, err error) error {
-               if err == nil {
-                       // all files should be owned by root:root
-                       err = os.Chown(name, 0, 0)
-                       if err != nil {
-                               return err
-                       }
-                       // remove any world permissions from the file
-                       err = os.Chmod(name, info.Mode().Perm()&0770)
-               } else if errors.Is(err, fs.ErrNotExist) {
-                       return nil
-               }
-               return err
+               return nil
        })
 }
```


Without fixing the permissions, I can inspect the contents of the installation directory without needing to be root. You can additionally see the execute permission is set for every file. I am able to execute the elastic-agent binary as a non-root user.

```sh
ls -la /Library/Elastic/Agent/data/elastic-agent-bda6f8
total 8
drwxr-xr-x   7 root  wheel   224 Feb 10 15:36 .
drwxr-xr-x   5 root  wheel   160 Feb 10 15:36 ..
drwxr-xr-x  47 root  wheel  1504 Feb 10 15:36 components
-rwxr-xr-x   1 root  wheel   227 Feb 10 15:36 elastic-agent
drwxr-xr-x   3 root  wheel    96 Feb 10 15:36 elastic-agent.app
drwx------   3 root  wheel    96 Feb 10 15:36 logs
drwxr-x---   6 root  wheel   192 Feb 10 15:36 run
❯ elastic-agent status
Error: failed to communicate with Elastic Agent daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/elastic-agent.sock: connect: permission denied"
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.6/fleet-troubleshooting.html
```

Note that executing the `elastic-agent` command still fails because the `/var/run/elastic-agent.sock` is created at runtime by the agent service which does run as root. This is more of a coincidental security block and not something we expect to have to depend on. 

Given that a non-root user can execute the agent binary this seems obviously less secure, and I would be worried about a way to escalate this to a situation where someone can take the agent offline with a simple `while elastic-agent restart; do :; done` loop in the shell if they can figure out how to bypass control socket permissions issue.  

> Create the .app bundle in a temp directory and fix it's permissions before copying to the final destination
Pros: low effort
Cons: not actually sure if this will work, could break again in the future

I didn't get a chance to test this as I haven't upgraded to Ventura yet, but it would be more secure even if it is temporary. It would by us time to do something that can work without comprising security long term.

My feeling is that as long as the agent is used as a security product we need to pick the most secure option. The third option would meet this criteria even if it is inconvenient to do.

**Comment by dedemorton** [comment]
Wanted to note that I also ran into this problem after upgrading to Ventura. But it went away when I uninstalled 8.6.0 (`sudo elastic-agent uninstall`) and installed 8.6.1 instead.

@nimarezainia
>(sorry not sure whom to forward this to) Could we add this to the past release-notes? We can craft the verbiage if required.
 
Use @elastic/ingest-docs going forward.

Yes, we can add to past release notes. Just [edit this file](https://github.com/elastic/observability-docs/edit/main/docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc). You can copy an existing entry under known issues (look under the section that starts at line 161 for 8.6.0). Make sure you change the ID of the new section to `[[known-issue-issue-2103]]` and include the whole block.

**Comment by nimarezainia** [comment]
@joshdover & @cmacknz  looks this would affect all releases from 8.5.0 including 8.6.0 - could you please let me know which releases exactly are affected?

@dedemorton (thank you for the pointer) if it affects multiple releases, I'll have to update for all correct?

**Comment by dedemorton** [comment]
@nimarezainia Yes. I can help you with the backports after you've added the section to one release.

**Comment by joshdover** [comment]
@cmacknz Thank you for the investigation, your conclusion to attempt option 3 makes sense to me. We will also need to test how upgrading may be affected as well, but this may not be a problem since the installation would be modified by the agent process itself rather than a separate installer process. 

> looks this would affect all releases from 8.5.0 including 8.6.0 - could you please let me know which releases exactly are affected?

Yes 8.5.x and newer

**Comment by nimarezainia** [comment]
Hi @dedemorton i created the PR: https://github.com/elastic/observability-docs/pull/2642  wouldn't give me a preview so hoping I got it right. Let me know.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have attempted to test the scenario shared under https://github.com/elastic/elastic-agent/issues/2103#issuecomment-1420670574
- However, when we attempted to upgrade MAC-12 VM to MAC-13, it went into unresponsive state due to capacity issues.

**Screenshots:**
![14](https://user-images.githubusercontent.com/77374876/218668023-098fc17e-b563-44e4-bd29-bfe7d7b5f931.JPG)
![17](https://user-images.githubusercontent.com/77374876/218668009-d872af2c-7860-431a-888d-1b7d298c6e05.JPG)
![20](https://user-images.githubusercontent.com/77374876/218668018-e5c3cfcd-11fa-4a05-9ba5-4f4a771f8b86.JPG)


Further we tried to install agent on fresh Ventura-13.2 and we are successfully able to install agent on 8.7 BC1 kibana cloud environment. [Full disk access not granted]

**Screenshot:**
![23](https://user-images.githubusercontent.com/77374876/218668379-9e768d84-f4bb-4d54-a44c-e4179a01e4c9.JPG)


**Build details:**
BUILD: 60614
COMMIT: d3b239d76aa04f073836f6100782134ac86887e2

Thanks
