### ISSUE TITLE
Reusable integration policies

### ISSUE THREAD

**Issue by nimarezainia** [elastic/elastic-agent#2227]
**Describe the enhancement:**
Currently the Elastic agents can only belong to single policy. Group of agents in a policy however may have different permutations of applications and data sources to to ingest data from. The 1:1 relationship between agent and the policy it belongs to therefore forces  our users to create multiple policies with some having the same integration configuration in multiple policies.

Ideally we could allow a base policy to inherit other "integrations policies" so that they can be used in other base policies. The user then would only need to configure the integration once (smaller management surface for them) and ad that policy to other policies. 

**Describe a specific use case for the enhancement or feature:**

**Comment by STRSistemas** [comment]
The truth is that before I found this issue, our technical team had also been missing this functionality for months. 

It would be a good improvement.

If you look at it from the "agent policy by server type" point of view, I want both my MySQL server types and my Kubernetes-node server types to have the "System" integration, but obviously you don't want/can't have MySQL integration on a Kubernetes node that doesn't have MySQL and vice versa.

If in this situation, having many "server types" we need to make a change in how the "System" integration is used we have to make the same change "N" times for each server type

**Comment by sunilemanjee** [comment]
This is similar to how policies are built with Splunk UF. Stacking.  Glad we are moving in the right direction.

**Comment by ironman-hythloday** [comment]
+1 for this feature: It would also follow the composable template convention from our Data Streams.  IHAC who would benefit greatly from this ( >1k Agents)

**Comment by Hythloday-zero** [comment]
+1 for this feature: It would also follow the composable template convention from our Data Streams. IHAC who would benefit greatly from this ( >1k Agents)

**Comment by jamesdowell2022** [comment]
**Barclays** mentioned something similar last year - building block policies for agent policies, e.g. a basic windows desktop or server policy that they can then add a specific integration to, like we have building block rules in SIEM. Comment from Barclays (low priority as they use standalone agent right now - deployed via MDM, in basic form - logs and metrics mostly):

We would also like to get the ability for the policy file to be built from multiple policies rather than everything having to be in one policy, this is due every server having a base policy then on top of that additional integrations would want to be added but only to some servers. We could end up with 100s of policies which would mean at present having to duplicate the base policies every time for the additional policies will lead to mistakes being made and if the base policy needed updating it would have to be done multiple times.

https://github.com/elastic/beats/issues/27442

**Comment by nerophon** [comment]
Further input from an enterprise user:
> One thing that this would need is security around the policies, space specific at least and auditing on who has changed a policy.

**Comment by nimarezainia** [comment]
> Further input from an enterprise user:
> 
> > One thing that this would need is security around the policies, space specific at least and auditing on who has changed a policy.

could you please unicast me more information on this request including who the user is and perhaps we can discuss with them live. thanks

**Comment by Oddly** [comment]
We are running into the same issue at the moment. Because of how our infrastructure is separated, we will end up with hundreds of policies.

**Comment by mbudge** [comment]
We are also running into this. 

Too many policies when elastic-agent is deployed in many network zones, on-prem, cloud, some collecting application logs, some collecting database logs etc. It get's complicated very quick. 

Would also be good to set the system integration metrics data direct to elasticsearch when using logstash for log data.

**Comment by user-987654321** [comment]
+1

**Comment by nimarezainia** [comment]
if you would like to try this feature in 8.15 (behind a feature flag and not GA) you may find the instructions [here](https://github.com/elastic/kibana/issues/188707#)

**Comment by jlind23** [comment]
@nimarezainia shouldn't we close this as fixed by. https://github.com/elastic/kibana/issues/75867.

**Comment by nimarezainia** [comment]
> [@nimarezainia](https://github.com/nimarezainia) shouldn't we close this as fixed by [elastic/kibana#75867](https://github.com/elastic/kibana/issues/75867)?

@jlind23 this feature is not GA as yet.

**Comment by AntoineFaul** [comment]
Why is this only available for enterprise license ? We have been waiting for multiple years for this feature, and despite paying for a platinium license, we are considering going back to manually deploying agent, because without these feature, it is hard to maintain integration configurations that is duplicated multiple times.

**Comment by nimarezainia** [comment]
Generally Available  in 8.16

**Comment by nimarezainia** [comment]
> Why is this only available for enterprise license ? We have been waiting for multiple years for this feature, and despite paying for a platinium license, we are considering going back to manually deploying agent, because without these feature, it is hard to maintain integration configurations that is duplicated multiple times.

We believe that this is a feature that brings a lot of operational efficiencies for more complex enterprise environments, therefore warranting an Enterprise license level.
