### ISSUE TITLE
8.8.0-SNAPSHOT report fleet status always as starting

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#2528]
Testing with 8.8.0-SNAPSHOT cloud deployment and elastic agent, I noticed that the fleet status remains to `STARTING` in the `elastic-agent status` when correctly enrolled into Fleet and having completed a few checkins already.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 8.8.0-SNAPSHOT (build: 8da86c6ca20039e37bc80bb87e371e23ff1502ee at 2023-04-20 03:01:45 +0000 UTC)
- Operating System: Linux
- Discuss Forum URL:
- Steps to Reproduce:
  - Enroll an agent in Fleet
  - Wait for a few minutes, then run `elastic-agent status`

**Comment by jlind23** [comment]
@pchila is this still accurate? I didn't any other mention of this problem yet.

**Comment by jlind23** [comment]
@amolnater-qasource @dikshachauhan-qasource is this a behaviour you recently faced on one of the 8.8 BC?

**Comment by pchila** [comment]
@jlind23  as of today I managed to reproduce with 8.8.0 BC2

**Comment by jlind23** [comment]
Thanks @pchila keeping it in the sprint as planned then.

**Comment by amolnater-qasource** [comment]
Hi @jlind23 

We have also revalidated this issue on latest 8.8 BC2 and observed that the **issue is reproducible** at our end too.

**Observations:**
- Fleet State is shown as `Starting` on running elastic-agent status command.

**Ubuntu22:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/f8ae01ba-ece3-4cb1-8c18-a3f29242f75e)

**Further the issue is also reproducible for the MAC agent:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/79a07256-5c29-4316-8350-c3058d6249ee)

**Build details:**
VERSION: 8.8.0 BC2
BUILD: 62857
COMMIT: 33efd47ee6927b54b328e901fe31d31eae875325
Artifact Link: https://staging.elastic.co/8.8.0-118443e6/summary-8.8.0.html

Please let us know if anything else is required from our end.

Thanks!
