### ISSUE TITLE
Heap profiles in diagnostics are unusable as of 8.6

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2530]
The heap profiles captured in the agent diagnostics starting in 8.6 are not usable, they contain no meaningful information. Prior to 8.6 these profiles used to contain the complete allocation graph. For example here is a heap profile captured from fleet-server:

![image](https://user-images.githubusercontent.com/3466215/233443636-5ae98fb1-68bf-4017-8141-dba9f0bf5135.png)

In 8.6 there was a change to how diagnostics were collected for Go programs. Diagnostics are now collected using diagnostic hooks in the Elastic Agent client package:

https://github.com/cmacknz/elastic-agent-client/blob/141cf7b58d33c0ad8b3fa427bbd3af9c32773437/pkg/client/client_v2.go#L783-L802

```go
func (c *clientV2) registerPprofDiagnostics(name string, description string) {
	c.RegisterDiagnosticHook(name, description, fmt.Sprintf("%s.txt", name), "plain/text", func() []byte {
		var w bytes.Buffer
		err := pprof.Lookup(name).WriteTo(&w, 1)
		if err != nil {
			// error is returned as the content
			return []byte(fmt.Sprintf("failed to write pprof to bytes buffer: %s", err))
		}
		return w.Bytes()
	})
}
```

This appears to have unintentionally broken heap diagnostics collection. Simpler diagnostics like the goroutine profile do appear to work correctly with this implementation.

**Comment by cmacknz** [comment]
In 8.5 and earlier we relied on being able to reach the /debug/pprof endpoint to collect profiles instead:

https://github.com/elastic/elastic-agent/blob/0e1a7396f356f8af5ad28c3c8e941256f50c86a2/internal/pkg/agent/control/server/server.go#L500-L518

**Comment by andrewkroh** [comment]
While trying to troubleshoot a suspected leak in 8.7.0 I just realized that the collected profiles are in the "legacy text format" instead of the gzip compressed protobuf format. In addition to fixing this problem, can I also request that we enable the `/debug/pprof` endpoints on the monitoring socket. For example, this is how Filebeat is run:

`/usr/share/elastic-agent/data/elastic-agent-fc4a15/components/filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${FILEBEAT_GOGC:100} -E filebeat.config.modules.enabled=false -E http.enabled=true -E http.host=unix:///usr/share/elastic-agent/state/data/tmp/filestream-monitoring.sock -E path.data=/usr/share/elastic-agent/state/data/run/filestream-monitoring`

If we added `-E http.pprof.enabled=true` to the arguments then I should be able to directly connect and get a profile with

`curl -v -o mem.pprof.gz --unix-socket /usr/share/elastic-agent/state/data/run/filestream-monitoring 'http:/debug/pprof/heap`

That would be extremely useful when trying to do several successive profiles.
