### ISSUE TITLE
Generalize `TestUpgradeFleetManagedElasticAgent` for various upgrade scenarios

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#2641]
## Background

In https://github.com/elastic/elastic-agent/pull/2292, a POC was created for an E2E testing framework.  As part of this POC an E2E test was written to test a very specific Elastic Agent upgrade scenario: from version `8.6.0` => `8.6.1`.

Later, the POC E2E testing framework was replaced by an extended version of the [existing integration test framework](https://github.com/elastic/elastic-agent/tree/main/pkg/testing) ([developer guide coming soon](https://github.com/elastic/elastic-agent/issues/2640)).  As part of this replacement, the upgrade test from the POC was ported over to the new framework in https://github.com/elastic/elastic-agent/pull/2618.

---

As a follow up to https://github.com/elastic/elastic-agent/pull/2618, we should generalize the upgrade test to handle more scenarios.  Quoting @cmacknz from https://github.com/elastic/elastic-agent/pull/2618#discussion_r1189083271:

> For fleet managed upgrades, we need to be able to parameterized the set of upgrades to attempt easily. At minimum we would want the following for regression purposes:
> 
> * 7.17 can upgrade to the current release.
> * 8.2 can upgrade to the current release (last release before encrypted configuration was introduced).
> * For release branches, the current version can upgrade to main.
> * The previous minor can upgrade to this version (what we have in this test).

**Comment by jlind23** [comment]
@faec - Assigning this to you as after discussing with @cmacknz this one takes precedence over the E2E work you were doing as it will unblock more possibilities.

**Comment by jlind23** [comment]
@cmacknz it looks like this covers also the issues below, am I right?
- #2429 
- #2430

**Comment by cmacknz** [comment]
Yes, with the exception that the managed Elastic Agent test above specifies that Elastic Defend should be installed for the duration of the test. 

They also mention upgrading the stack but I don't think we need to do that in these tests, we should just use the correct stack version for the branch we are on (e.g 8.9.0-SNAPSHOT for main and 8.8.2-SNAPSHOT for 8.8 at the time of writing).

**Comment by blakerouse** [comment]
This work was completed with my refactor of the upgrade tests.

We now test upgrading from the last major and two-minors using the the Elastic Control socket, as well as test upgrade through the Fleet API for the current Elastic Agent version. This ensures that the Elastic Agent can upgrade from previous versions as well as the current version has not broken its ability to receive a action to perform an upgrade to another version.

There is no benefit in testing that older versions can receive actions because that should have already been validated and if those end up broken its not an effect of the current Elastic Agent under test.
