### ISSUE TITLE
Deadlock can occour if VarsWatcher (or other components) overload CheckinExpected components

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent#2691]
Probably related: https://github.com/elastic/elastic-agent/issues/2628

The `runtimeComm` component has a `checkinExpected` channel that's used to track updates to the state of a unit:
https://github.com/elastic/elastic-agent/blob/a05e24ad067917c1525656f923cfe0d40b37ff36/pkg/component/runtime/runtime_comm.go#L92

If the buffer on this channel fills up and channel sends begin to block (which can happen in cases where unit config updates are happening faster than unit Checkin events, as is sometimes the case with k8s installs with container providers), this will cause the `manager.update()` method to block while it holds a mutex:

https://github.com/elastic/elastic-agent/blob/a05e24ad067917c1525656f923cfe0d40b37ff36/pkg/component/runtime/manager.go#L655-L657

As the `manager.update()` method tries to send to a component that also becomes blocked when the `checkinExpected` channel blocks here:
https://github.com/elastic/elastic-agent/blob/a05e24ad067917c1525656f923cfe0d40b37ff36/pkg/component/runtime/manager.go#L674

That `Update()` call is implemented here:
https://github.com/elastic/elastic-agent/blob/a05e24ad067917c1525656f923cfe0d40b37ff36/pkg/component/runtime/command.go#L241-L244

And the method that reads from that `compCh` channel, `commandRuntime.Run`, is blocked because of a call to CheckinExpected():

https://github.com/elastic/elastic-agent/blob/a05e24ad067917c1525656f923cfe0d40b37ff36/pkg/component/runtime/command.go#L149

Which is blocked by a send to the full `c.checkinExpected` channel:

https://github.com/elastic/elastic-agent/blob/a05e24ad067917c1525656f923cfe0d40b37ff36/pkg/component/runtime/runtime_comm.go#L171-L172C31

This becomes a problem when the `manager.getCertificate()` tries to acquire that mutex, which it never will:
https://github.com/elastic/elastic-agent/blob/a05e24ad067917c1525656f923cfe0d40b37ff36/pkg/component/runtime/manager.go#L807-L820

The `getCertificate()` callback is called during the gRPC TLS handshake. However, the gRPC `CheckinV2` call is the only codepath that drains the aforementioned `checkinExpected` channel, meaning that the agent is effectively deadlocked at this point.

There's a few ways to fix this:
1. change the mTLS system so we don't need a `getCertificate()` callback.
2. make the `runtime.Update()` method non-blocking.
3. make the `runtimeComm.CheckinExpected()` method non-blocking
4. Use a more complex queue setup to handle checkinExpected events from other components instead of just a buffered channel

## Reproducing

Reproducing this is a bit difficult, as it requires the agent component managers to send a large number of unit updates. In the wild, this is often caused by the VarsWatcher component, which gets updates from the Docker/k8s provider:
https://github.com/elastic/elastic-agent/blob/a05e24ad067917c1525656f923cfe0d40b37ff36/internal/pkg/agent/application/coordinator/coordinator.go#L692-L698

That call to `processVars` will eventually call `manager.Update()`, which in turn calls `runtime.Update()`, which will end up populating that channel via `comm.CheckinExpected()`. The best way to reproduce this is to run the agent in an active k8s environment with the various container providers enabled.

**Comment by jlind23** [comment]
> If the buffer on this channel fills up and channel sends begin to block (which can happen in cases where unit config updates are happening faster than unit Checkin events, as is sometimes the case with k8s installs with container providers), this will cause the manager.update() method to block while it holds a mutex:

@fearful-symmetry @blakerouse @cmacknz what is so specific in k8s install that can cause the unit config update mechanism to be overloaded? Could this be linked to the number of integrations installed?

cc @amitkanfer

**Comment by cmacknz** [comment]
This is the test we added to reproduce the problem: https://github.com/elastic/elastic-agent/blob/953fda060f317c2389ef6fd1cac8806a2bfe92ac/pkg/component/runtime/manager_test.go#L801-L939

What it does is continuously update the state of a unit for a running component. This is equivalent to something like Beats spamming the Elastic Agent with status changed, like alternating between the CONFIGURING and HEALTHY state constantly. The exact event doesn't matter, but rather the volume of events.

We don't have any logs that let us tell exactly why this problem was getting triggered, but there are two common differences between agents that run on Kubernetes and those that don't that are probably contributing:

1) The number of individual inputs for an agent running on Kubernetes is usually proportional to the number of containers running on a node. This results in a much higher number of total inputs, in some cases this can be 100s.
2) The number of containers monitored is dynamic. Containers and nodes in a cluster stop and start constantly, because of scale ups, cron jobs, or even misbehaving applications in the container that crash frequently.

In large Kubernetes clusters agent is usually running a much larger number of inputs, with those inputs possibly changing regularly. This isn't the case when Elastic Agent is running on a single endpoint or a standalone Linux server.

The number of integrations definitely increases the load on the agent, but you don't need a lot of integrations installed to end up with a highly loaded agent.
