### ISSUE TITLE
Minimum Requirements for disk are not accurate

### ISSUE THREAD

**Issue by markwalkom** [elastic/elastic-agent#2759]
This was raised at https://discuss.elastic.co/t/elastic-agent-8-8-0-disk-space-requirement/334723

In https://www.elastic.co/guide/en/fleet/8.8/elastic-agent-installation.html under `Minimum Requirements` we mention;
> Disk | 640 MB
However we are now bundling all the component binaries instead of downloading on demand which changes this size.

Can we please update the docs to better reflect what the requirements are here.

**Comment by jlind23** [comment]
@nimarezainia Could you take care of this please?

**Comment by nimarezainia** [comment]
@jlind23 I think we may need to redo the whole minimum requirements that your team did sometime ago and update. Unless you think just the disk space has changed.

**Comment by jlind23** [comment]
@nimarezainia dispace has changed due to the fact that some components are heavier in 8.8. Osquery is now 3 times bigger from 30 to 90mb. @kevinlog @aleksmaus  do you recall any changes that may have affected osquery size?
<img width="2111" alt="Screenshot 2023-06-05 at 07 15 53" src="https://github.com/elastic/elastic-agent/assets/43535167/faeecac7-dee5-4a99-b9e9-3b86fb3b7bb9">

**Comment by kevinlog** [comment]
@aleksmaus is it related to this change? https://github.com/elastic/beats/pull/34565

**Comment by aleksmaus** [comment]
> @aleksmaus is it related to this change? [elastic/beats#34565](https://github.com/elastic/beats/pull/34565)

That change was to uncompress osquery.app bundle from osquery-5.7.0.pkg during the build/packaging phase. 
Before that change the osquery.app bundle was extracted during the first time osquerybeat was activated by the agent.

So yeah, if you compare the INITIAL size on the disk right after the agent is installed the size before that change would be smaller because you would only have compressed .pkg file on the disk instead of uncompressed app bundle.
But if you compare the size after osquerybeat was run ("installed" osqueryd binary and certs) then the size would be unchanged, since in both cases you will have the osquery.app bundle on the disk instead.

What are we comparing here?

**Comment by janniten** [comment]
Just to add some information. Today I've updated agents on Linux, from version 8.4.2 to 8.8.1 and also observed a considerable increment in the use of disk space (+970MB. almost 50% more)
In Linux (depending how the fs are mounted) also the /opt/Elastic is in the root directory, which can be a problem, your system will be blocked if the root partition is full.
Thank you

**Comment by eedugon** [comment]
I would suggest to raise a separate issue if we consider that the high disk utilization and increase that we are recently facing is an issue to solve, as this issue is related with the accuracy of the documentation only :)

**Comment by mbudge** [comment]
Isn’t 1.7gb in /opt too much?

Had to get IT to increase a volume recently as elastic agent wouldn’t install as /opt became full.

Going to hold off upgrading in case this impacts our production servers.

**Comment by mbudge** [comment]
Is this because logs are getting written to the /opt folder?

If so that needs to stop as it will cause system stability issues.

**Comment by pierrehilbert** [comment]
Since 8.6 we changes how the Agent is built and it now includes all subcomponent instead of downloading them on demand.
That's the main reason to explain this increase.

**Comment by bczifra** [comment]
@jlind23 @nimarezainia @cmacknz can we please get the documentation updated to indicate current storage requirements?

**Comment by kilfoyle** [comment]
@jlind23 I had [this PR](https://github.com/elastic/ingest-docs/pull/342) open to update the disk space requirements. I closed it since @nimarezainia [mentioned](https://github.com/elastic/ingest-docs/pull/342#issuecomment-1647207591) yesterday that he's planning to open PRs after he's collected data.

**Comment by kilfoyle** [comment]
With a big thanks to @nimarezainia for collecting the data, the documented [minimum requirements](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html#_minimum_requirements) are now up to date for versions 8.1 up to current.

**Comment by pierrehilbert** [comment]
Thanks @nimarezainia and @kilfoyle for the work you have done here!

**Comment by swtrux** [comment]
1.7GB for this package size is way too big.  We are looking at moving to elastic-agent but can't have over 2000 servers remade to support the increase in size needed?  The beats are supposed to be lightweight.  Currently metricbeat and filebeat installed together on a system only takes up 5.8M of space.  Now that is lightweight, how can I explain to my customer that I need to expand from 5.8M to 1.7GB??

**Comment by janniten** [comment]
@swtrux, in addition when you upgrade the agent you'll need twice the space: all binaries are downloaded again, unpacked and then all old binaries are deleted.
I decided to put the agent in a dedicated partition (/opt/Elastic) that now has 4.1GB and when I perform an update it fails because it reached 100%.
I agree with you that only necessary binaries should be installed

**Comment by cmacknz** [comment]
For some context we used to download the less frequently used binaries on demand. The problem with this approach was that this download would fail at runtime. We have agents deployed on unreliable networks, and these downloads would fail at runtime.

In this case each upgrade of the agent needs multiple successful downloads, one of the minimal base installation package, and one for the each version of the extra binaries.

So there is a trade off here between the reliability and total time required to upgrade and the disk space required to install. We have shifted to favor using more disk space.

That said I agree the current size of the agent is too large, but at the same time if we just start downloading all binaries on demand we are just shifting the problem somewhere else. We use less disk by default but we make upgrades more complex and more likely to fail (there are more steps and the network quality isn't in our control).

We have to work out the correct compromise, which may be supporting both methods (download everything or pre-install everything).

**Comment by swtrux** [comment]
@cmacknz I think a good path would be to allow an advanced configuration method where you give more flexibility to the end user to decide what would be included in the base Agent package.  I know this would bring more complexity so I think you should keep the "easy" button for users who are not concerned about space but allow custom configuration for users who have space concerns.  In most cases the end user knows exactly what integrations(modules) they are going to be using, allowing them to create a custom agent installation package holding just what is needed would allow only taking up the space that is needed.  Then having everything available in the repository for download would allow adding new things when a decision is made to expand.

For example, we are moving to using Agent in stages.  Our first goal is to just get Agent and Fleet deployed and bring the new OS Query feature.  We will be keeping the legacy beats (Metricbeat, Filebeat, Heartbeat, Winlogbeat).  So deploying the current Agent package brings a 2nd copy of the beats we are already deploying which complicates the space issue even more.  I want to be able to add Metricbeat to the Agent package when we are ready to transition.

**Comment by cmacknz** [comment]
Allowing users to customize what gets included in the agent package definitely leads to the optimal on disk size, but it also brings significant complexity as we'd need to build and support an easy way to allow this (probably in Kibana). We're thinking about a few ways to address this, that solution probably isn't the first thing we'll attempt due the complexity involved.

**Comment by swtrux** [comment]
I (and many others) would be happy with a manual way to do it outside of Kibana (for advanced user) until you are able to build this in Kibana.

**Comment by SergeyNosko** [comment]
1.7GB. Just for a record, the full size of system we are going to observe is less including OS and tools.
It might be no go decision for people to use elastic agent despite fleet convenience.
