### ISSUE TITLE
Integration tests: test upgrades including grace period

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#2796]
**Describe the enhancement:**
In agent integration tests it should be possible to fully test the upgrade process by waiting for the grace period to expire thus confirming that the upgrade is successful. 
Currently we cannot do that because the test would time out first (see https://github.com/elastic/elastic-agent/pull/2752)
We need to either increase the timeout of the tests or reduce the grace period used by agent in integration tests (maybe as proposed [here](https://github.com/elastic/elastic-agent/pull/2752#discussion_r1220088067)

**Describe a specific use case for the enhancement or feature:**
Any upgrade scenario that needs to be tested using integration tests

**What is the definition of done?**
Upgrade integration test can wait for the upgrade to be completed (including the grace period) without timing out

**Comment by cmacknz** [comment]
+1 to allowing us to reduce the grace period rather than having a test that always takes 10+ minutes.

**Comment by pierrehilbert** [comment]
Should we add this to this list: https://github.com/elastic/elastic-agent/issues/2176 ?

**Comment by cmacknz** [comment]
Yes

**Comment by ycombinator** [comment]
The general approach I'm thinking of taking here is:
- Add upgrade watcher settings (grace period, etc.) to Agent configuration.  TBD on whether we should document these and include them in the reference configuration file, as we most likely don't want end-users messing around with these.
- Have the `watch` sub-command load the Agent configuration file, read these settings, and use them instead of the hardcoded constants today.  The constants will serve as default values for these settings.
- Provide tooling in the testing framework to modify the default Agent configuration before Agent is installed and run.  Upgrade tests can use this tooling to reduce the upgrade watcher grace period, etc. as part of the test.

**Comment by cmacknz** [comment]
> TBD on whether we should document these and include them in the reference configuration file, as we most likely don't want end-users messing around with these.

You may as well document it to save future developers time in discovering this exists, I can't see users modifying this unless we give them a reason to do it. I could see us choosing to set this value to zero as a way of disabling the watcher if we ever find a bug in it, which might be useful in support cases.

I think just putting this in the main agent configuration file is fine, adding the .dev.yml file is additional complexity to protect us from an unlikely outcome. Realistically anyone who can figure out what the upgrade watcher configuration does can also figure out the .dev.yml file exists and just try to use that instead.
