### ISSUE TITLE
Upgrade marker is not removed on Windows

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#3027]
While enabling the Windows integration testing runner I hit an issue where `checkUpgradeWatcherRan` [code](https://github.com/elastic/elastic-agent/blob/main/testing/integration/upgrade_test.go#L475) would always fail. Digging into the Elastic Agent code I found this line:

https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/cmd/watch.go#L116

Which does not remove the watcher on Windows. It is not clear as to why this is being done. I was unable to determine from the original watcher PR or any other follow up PR's why this was needed. The code comment is also not clear as to why.

For now in the test I have chosen to skip checking for the market to be removed on Windows. I think we need to determine if this code can be changed to work the same on Windows as it is on all the other platforms.

**Comment by cmacknz** [comment]
@michalpristas originally added this in https://github.com/elastic/elastic-agent/commit/374ef1f7744b034a1f75d7c07fae90eec25e3b23#diff-86a2022065947a87c679c95519c01fe664e1e07d2c899a31ee7115f7b5c79beb

@michalpristas do you remember why we don't remove the upgrade marker on Windows?

https://github.com/elastic/elastic-agent/blob/05e7d689cd39e55a018b26f14cf70014f2695f00/internal/pkg/agent/cmd/watch.go#L113-L117

**Comment by michalpristas** [comment]
i was looking at the code and i don't really remember why windows is handled separately. it had to be some failure on removal i encountered during testing due to some windows specific lock, but looking at it now i can't imagine how.

**Comment by blakerouse** [comment]
@michalpristas Thanks for looking at it.

I think the best path forward is to keep it how it is. Get the Windows integration tests working and this try to remove this behavior. Want to ensure that changing this behavior doesn't break upgrades.

**Comment by jlind23** [comment]
@blakerouse is this issue still relevant or can it be closed now?
cc @ycombinator

**Comment by ycombinator** [comment]
I think this issue can be safely closed now but will let @blakerouse confirm.

**Comment by ycombinator** [comment]
Reopening. We traced reports of agents stuck in UPG_WATCHING after every Windows upgrade back to this code path.

When the upgrade watcher completes a successful watch (grace period passes, agent healthy throughout), it reaches this branch in `watchCmd`:

```go
// cleanup older versions,
// in windows it might leave self untouched, this will get cleaned up
// later at the start, because for windows we leave marker untouched.
removeMarker := !isWindows()
```

On Windows `removeMarker` is false, so the upgrade marker is never removed after a successful watch. The agent continues reporting `UPG_WATCHING` to Fleet indefinitely. The "cleanup later at start" only happens when a new watcher process starts and finds the grace period already expired — which requires a service restart.

There is no automatic trigger for that restart, so the agent stays stuck in `UPG_WATCHING` until the Windows service is manually restarted. At that point the new watcher takes the "not within grace" cleanup path, removes the marker, and the agent reports healthy. This is why manual restart consistently fixes the symptom without addressing the root cause.

The original reason for this Windows exception is unknown (see the earlier discussion in this thread). Given that it causes every Windows upgrade to leave the agent stuck in `UPG_WATCHING`, it should be fixed regardless.

**Comment by ycombinator** [comment]
@ebeahan Reopening per last comment; will need prioritization.

**Comment by ycombinator** [comment]
Never mind, ignore https://github.com/elastic/elastic-agent/issues/3027#issuecomment-4444124773.  The `removeMarker := !isWindows()` line only happens when the Upgrade Watcher has set the upgrade details state to `UPG_COMPLETED`.  So the scenario I saw (in an SDH) with an Agent running on Windows being stuck on `UPG_WATCHING` cannot be attributed to this issue.  Closing again.

**Comment by macdewee** [comment]
The current status is that the upgrade marker is kept on Windows. We keep it right after the upgrade process, so agent can read and report successful operation to the Fleet Server.

For the record, we took two different approaches to unify behavior for Linux and Windows:
- remove the upgrade marker by  the agent after successful operation report to Fleet Server: https://github.com/elastic/elastic-agent/pull/14937
- create second marker just to leave trace of successful upgrade: https://github.com/elastic/elastic-agent/pull/15674

See the discussion there for more details, but finally we decided to not merged them due to upgrade marker ownership concern, or necessity of keeping upgrade marker as a fallback anyway

It is also worth to mention the idea to use windows registry instead of file system for the windows upgrade process

Anyway, the current behavior is harmless and well-tested in practice, so I am leaving the issue closed.
