### ISSUE TITLE
Kafka output error is displayed for Elastic Defend on 8.12.0 BC2.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3936]
**Kibana Build details:**
```
VERSION: 8.12.0 BC2
BUILD: 69899
COMMIT: 15a6cc8236b4828b97da733746ec36bd33f03bba
Artifact Link: https://staging.elastic.co/8.12.0-f6277726/downloads/beats/elastic-agent/elastic-agent-8.12.0-windows-x86_64.zip
```

**Host OS:**  Windows

**Preconditions:**
1. 8.12.0 BC2 Kibana cloud environment should be available.
2. 8.12.0 Agent should be installed using agent policy having Elastic Defend integration.
3. Kafka broker should be setup.

**Steps to reproduce:**
1. Select output for integrations as Kafka.
2. Observe agent gets unhealthy and observe output not supported error for Defend integration.

**Validated as working fine under:**
https://github.com/elastic/endpoint-dev/issues/13192#issuecomment-1833616128

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/b66b0c47-75e5-47ca-a048-78ca9ed4737c)

**Expected Result:**
As per https://github.com/elastic/endpoint-dev/issues/13192 Kafka output should be supported for Elastic Defend on 8.12.0 BC2.

**Logs:**
[elastic-agent-diagnostics-2023-12-20T11-32-54Z-00.zip](https://github.com/elastic/elastic-agent/files/13726758/elastic-agent-diagnostics-2023-12-20T11-32-54Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by pierrehilbert** [comment]
@nfritts Keep me honest here but it should be supported in 8.12 right?

**Comment by nfritts** [comment]
Yeah, Kafka should be supported in 8.12

**Comment by intxgo** [comment]
Hey Agent team, something werid happened with the diagnostics.zip. There's so many empty directories inside agent's log dir, but no `services` dir with Endpoint logs. Also the `components/endpoint*` diagnostics didn't succeed.

**Comment by cmacknz** [comment]
`output not supported` is coming from the agent and it is refusing to start endpoint because the specification file says it doesn't support Kafka on Windows or MacOS.

Fix is in https://github.com/elastic/elastic-agent/pull/3941

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.12.0 BC4 kibana cloud environment and found it still reproducible.

**Observations:**
- No data for Windows agent under kafka broker topic when used with Elastic Defend.
- Data for System integration is visible with same broker.
- Agent with Elastic Defend gets unhealthy under Agents tab.

**Build details:**
VERSION: 8.12.0 BC4
BUILD: 70016
COMMIT: c2fda4713eb89786cf07dba596f6d45136858fd5

**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/77374876/085862d1-5bbd-4054-aa5f-848521a68c5c


**Logs:**
[elastic-agent-diagnostics-2024-01-03T12-34-33Z-00.zip](https://github.com/elastic/elastic-agent/files/13819837/elastic-agent-diagnostics-2024-01-03T12-34-33Z-00.zip)


**Agent.json:**
[ec2amaz-9edrhhs-agent-details.zip](https://github.com/elastic/elastic-agent/files/13819833/ec2amaz-9edrhhs-agent-details.zip)


Hence we are **reopening this issue**.

Please let us know if we are missing anything here.
Thanks

**Comment by nfritts** [comment]
I'm not going to be able to fully troubleshoot this, @intxgo or @brian-mckinney will have to look at it, but I found a lot of 'Message Timed out' errors for Kafka in Endpoints logs, but i think they're overall probably caused by this message:
`{"line":54,"name":"KafkaClient.cpp"}}},"message":"KafkaClient.cpp:54 Kafka Error: Local: SSL error [-181] | ssl://34.172.6.245:9094/1: SSL handshake failed: error:0A000086:lib(20)::reason(134): broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (add broker's CA certificate to the Windows Root certificate store) (after 41ms in state SSL_HANDSHAKE, 5 identical error(s) suppressed)","process":{"pid":1000,"thread":{"id":1888}}}`

**Comment by intxgo** [comment]
Initial analysis:

The Kafka output was configured with ssl, as we can confirm by the config (and provided video)
```
output:
  kafka:
    broker_timeout: 30
    client_id: Elastic
    compression: none
    headers: []
    hosts:
    - <REDACTED>
    partition:
      random:
        group_events: 1
    required_acks: 1
    ssl:
      certificate: <REDACTED>
      key: <REDACTED>
      verification_mode: full
    timeout: 30
    topics:
    - topic: qas-test
    type: kafka
    version: 2.6.0
```

Intresting Endpoint logs
```
"message":"Response.cpp:393 Policy action configure_output: success - Successfully read output configuration"
"message":"Comms.cpp:1325 Read Kafka output config:"
"message":"Comms.cpp:1140     hosts:"
"message":"Comms.cpp:1143       - amol-nater-kafka.qasource.elastic.dev:9094"
"message":"Comms.cpp:1145     auth_type:         ssl"
"message":"Comms.cpp:1146     compression:       none"
"message":"Comms.cpp:1147     compression level: 4"
"message":"Comms.cpp:1148     partitioner:"
"message":"Comms.cpp:1149       type: random"
"message":"Comms.cpp:1162     default topic:     qas-test"

"message":"KafkaClient.cpp:320 kafka config: bootstrap.servers=amol-nater-kafka.qasource.elastic.dev:9094|compression.codec=none|compression.level=0|delivery.timeout.ms=30000|enable.ssl.certificate.verification=true|error_cb=class std::function<void __cdecl(class kafka::Error const & __ptr64)>|log_cb=class std::function<void __cdecl(int,char const * __ptr64,int,char const * __ptr64)>|request.required.acks=1|request.timeout.ms=30000|security.protocol=ssl|ssl.ca.pem=*|ssl.certificate.pem=*|ssl.endpoint.identification.algorithm=https|ssl.key.pem=*"

"message":"KafkaClient.cpp:54 Kafka Error: Local: SSL error [-181] | ssl://34.172.6.245:9094/1: SSL handshake failed: error:0A000086:lib(20)::reason(134): broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (add broker's CA certificate to the Windows Root certificate store) (after 38ms in state SSL_HANDSHAKE, 3 identical error(s) suppressed)","process":{"pid":1000,"thread":{"id":3528}}}
```

Certificate validation is the problem. I've never seen yet such error so I'm not sure it's the problem, but it's very suspicious, that the kafka error indicates IP instead of DNS name:
- error: `ssl://34.172.6.245:9094`
- actual configuration: `amol-nater-kafka.qasource.elastic.dev:9094`

This can cause host name verification error as the certificate most likely have DNS name `amol-nater-kafka.qasource.elastic.dev` included instead of the IP.

This should be debugged further in the environment where it's occurring. OpenSSL utility `s_client` can confirm or show us details of the SSL handshake failure (substitute correct arguments)
```
openssl s_client -connect your-kafka-server:9093 -cert your-client.pem -key your-client-key.pem -CAfile your-ca.pem -debug
```

Otherwise, we would need to know further about the environment configuration to replicate it locally. How the certificates were generated and exact steps to configure Kafka server.

**Comment by amolnater-qasource** [comment]
Hi Team,

Please refer to these logs, where Windows agent is connected through username/password auth to the Kafka broker.
- Agent is freshly installed for just reproducing this issue.


**Logs:**
[elastic-agent-diagnostics-2024-01-04T12-40-23Z-00.zip](https://github.com/elastic/elastic-agent/files/13829892/elastic-agent-diagnostics-2024-01-04T12-40-23Z-00.zip)

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/9d9dc0a8-8df9-40a7-8ff8-fc4eaa8a7543)

https://github.com/elastic/elastic-agent/assets/77374876/961807cb-b171-4711-92bf-ba8a243dcfe9


Certs logs might be due to the reported issue https://github.com/elastic/kibana/issues/174227

Please let us know if anything else is required from our end.
Thanks!

**Comment by intxgo** [comment]
The additional error has the same root cause, certificate validation.

It's a Kibana UI bug to display "Elasticsearch connection failure" when the output is configured to Kafka. The reason of the error is the lack of Endpoint's policy response which should arrive from Kafka in this setup (historically Elasticsearch was the only output).

Endpoint was configured to send documents to Kafka, with user/password auth
```
output:
  kafka:
    broker_timeout: 30
    client_id: Elastic
    compression: none
    headers: []
    hosts:
    - <REDACTED>
    partition:
      random:
        group_events: 1
    password: <REDACTED>
    required_acks: 1
    sasl:
      mechanism: PLAIN
    ssl:
      verification_mode: full
    timeout: 30
    topics:
    - topic: qas-auth2
      when:
        contains:
          event:
            dataset: system.cpu
    - topic: qas-auth3
      when:
        contains:
          event:
            dataset: endpoint.events.network
    - topic: qas-auth
    type: kafka
    username: elastic
    version: 2.6.0
```

Interesting logs
```
"message":"Comms.cpp:1325 Read Kafka output config:"
"message":"Comms.cpp:1140     hosts:"
"message":"Comms.cpp:1143       - amol-nater-kafka.qasource.elastic.dev:9093"
"message":"Comms.cpp:1145     auth_type:         user_pass"
"message":"Comms.cpp:1146     compression:       none"
"message":"Comms.cpp:1147     compression level: 4"
"message":"Comms.cpp:1148     partitioner:"
"message":"Comms.cpp:1149       type: random"
"message":"Comms.cpp:1162     default topic:     qas-auth"
"message":"Comms.cpp:1166   topics:"
"message":"Comms.cpp:1169     - topic: qas-auth2"
"message":"Comms.cpp:1172       condition: contains"
"message":"Comms.cpp:1173       field:     event.dataset"
"message":"Comms.cpp:1174       value:     system.cpu"
"message":"Comms.cpp:1169     - topic: qas-auth3"
"message":"Comms.cpp:1172       condition: contains"
"message":"Comms.cpp:1173       field:     event.dataset"
"message":"Comms.cpp:1174       value:     endpoint.events.network"

"message":"KafkaClient.cpp:320 kafka config: bootstrap.servers=amol-nater-kafka.qasource.elastic.dev:9093|compression.codec=none|compression.level=0|delivery.timeout.ms=30000|enable.ssl.certificate.verification=true|error_cb=class std::function<void __cdecl(class kafka::Error const & __ptr64)>|log_cb=class std::function<void __cdecl(int,char const * __ptr64,int,char const * __ptr64)>|request.required.acks=1|request.timeout.ms=30000|sasl.mechanism=PLAIN|sasl.password=*|sasl.username=*|security.protocol=sasl_ssl|ssl.ca.pem=*|ssl.endpoint.identification.algorithm=https"

"message":"KafkaClient.cpp:54 Kafka Error: Local: SSL error [-181] | sasl_ssl://34.123.179.179:9093/1: SSL handshake failed: error:0A000086:lib(20)::reason(134): broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (add broker's CA certificate to the Windows Root certificate store) (after 42ms in state SSL_HANDSHAKE)"
```
@brian-mckinney can you confirm that the output config looks good? Is the `ssl: verification_mode: full` expected with user/password authentication? The client certificate is not provided this time.

**Comment by brian-mckinney** [comment]
@amolnater-qasource I looked at the diagnostics and checked out the other components.  From what I can tell, it appears that Elastic Defend is the only component that has a `kafka` output set.  Is that correct?  It looks like the beats and agent have an `elasticsearch` output enabled.

If that is true, it makes the possibility of a configuration issue more likely.  My guess is that since `verification_mode: full` is set, the Endpoint will need a certificate authority provided in order to validate the server.

We can test this by configuring one of the other components to use the same kafka output and see if they encounter a similar problem.

**Comment by amolnater-qasource** [comment]
Hi @brian-mckinney 

We have revalidated this issue with latest 8.12.0 BC5 kibana cloud environment and found it **still reproducible**.

**Observations:**
- Data for System integration gets populated on kafka broker.
- No Data for Defend integration is available.
- Agent gets unhealthy and Elastic Defend shows error under Agent details tab.

Further we don't add Server SSL certificate authorities while creating output as it is optional and System integration works fine without adding the same.

![image](https://github.com/elastic/elastic-agent/assets/77374876/0bc1ddf4-bba0-4a74-8516-9c4fa09c4562)


**Logs:**
[elastic-agent-diagnostics-2024-01-08T10-48-30Z-00.zip](https://github.com/elastic/elastic-agent/files/13859012/elastic-agent-diagnostics-2024-01-08T10-48-30Z-00.zip)


**Kafka broker topic output:**
[kafka-topic.txt](https://github.com/elastic/elastic-agent/files/13859001/kafka-topic.txt)

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/fc2dd979-647e-4bf2-8bdd-7d4bf25e8c7a)
![image](https://github.com/elastic/elastic-agent/assets/77374876/2b83554e-789f-4e60-8b2e-878a9dd801a0)


**Build details:**
VERSION: 8.12.0
BUILD: 70053
COMMIT: db9b8921b37139cbb1e11d23f6381f655edeb72b
Artifact Link: https://staging.elastic.co/8.12.0-9f05a310/downloads/beats/elastic-agent/elastic-agent-8.12.0-windows-x86_64.zip

Please let us know if we are missing anything here.

Thanks

**Comment by brian-mckinney** [comment]
@amolnater-qasource,  I am looking over the new diagnostics now.  In the meantime, could you try one thing for me?

- Try adding the CA cert for the kafka server to the configuration (the one that says it is optional).  If it connects successfully then that will narrow down the scope of the problem.

- My theory is that your kafka server is using a self signed cert (is it?)  If that is the case, then Endpoint likely won't trust the server with the local trust chain alone.

- But if that were the case, I would think beats would have a similar problem.  But it appears that they are connecting to kafka without issue.

@faec Do you have any insight from a beats perspective you could provide?

**Comment by amolnater-qasource** [comment]
Hi @brian-mckinney 

Thank you for the update.

>Try adding the CA cert for the kafka server to the configuration (the one that says it is optional). If it connects successfully then that will narrow down the scope of the problem.

We added that, and still the issue is not resolved.

Used cert downloaded with below command:
![image](https://github.com/elastic/elastic-agent/assets/77374876/63f43372-487c-4de5-a3c2-7bdbfae9f5fa)
![image](https://github.com/elastic/elastic-agent/assets/77374876/8a956b56-5c44-4810-8b03-2ca62c86b9cc)


>My theory is that your kafka server is using a self signed cert (is it?) If that is the case, then Endpoint likely won't trust the server with the local trust chain alone.

Yes, these certs are self-signed, which was implemented under https://github.com/elastic/security-team/issues/7408
Could you please confirm @cavokz and add anything if we are missing anything.

Please let us know if anything else is required from our end.
Thanks!

**Comment by amolnater-qasource** [comment]
Thank you for sharing the details. @cavokz 

It shows below output for `openssl s_client -connect kafka-server:port` command:

![image](https://github.com/elastic/elastic-agent/assets/77374876/81c09565-b473-4882-a687-872b294d4aed)

**Comment by amolnater-qasource** [comment]
We have attached the output for 9093 port in the file below:
[Kafka-ssl.txt](https://github.com/elastic/elastic-agent/files/13862887/Kafka-ssl.txt)

Thanks!

**Comment by brian-mckinney** [comment]
@cavokz @amolnater-qasource Is there any way I could access your kafka broker? Or can you provide instructions on how I could set it up via your scripts?  I believe I need to test against a kafka broker with a CA signed certificate like you guys are (Lets Encrypt)  all my testing has been done with a self signed certificate.

**Comment by brian-mckinney** [comment]
### The issue with Endpoint was this:

- The LetsEncrypt CA cert was created for the FQDN, however the ADVERTISED_LISTENERS in the kafka server config were set to the IP address

- The FQDN obviously resolves to the IP address 

- Endpoint connected to the Kafka host (FQDN) using the `librdkafka` library, so far so good

- One of the first things `librdkafka` does is refresh its broker metadata, so it asks the broker it is connected to what it is advertised as, and the broker returns `sasl_ssl://123.123.123.123:9093` rather than `sasl_ssl://kafka-fqdn:9093` since that was what the docker config had set as the ADVERTISED_LISTENER

- `librdkafka` then attempts to validate the certificate for  `sasl_ssl://123.123.123.123:9093`, but now the hostname's don't match!  and since `certificate_verification_mode` was set to `full` that is a deal breaker and we refuse to continue talking to the kafka broker

@amolnater-qasource, can you please run the test again with the new kafka stack that @cavokz posted in the above comment?

### Takeaways:
- I don't believe Endpoint needs to change anything, it was a configuration issue that was the root of the problem

- However, it is unknown why beats/agent did not run into the same problem.  My guess is that it has to do with differences in how `librdkafka` and `sarama` libraries handle their broker connections

@faec @cmacknz @nfritts

**Comment by faec** [comment]
> it is unknown why beats/agent did not run into the same problem

This is the main thing that concerns me from the Beats side. We've definitely seen Beats reject Kafka connections because the certificate hostname didn't match, so it's not something as simple as skipping the check, but in that case I'm not sure what the scope of the behavior might be... I wonder if it's something like allowing deprecated common name matching or similar?

**Comment by brian-mckinney** [comment]
@faec I think this may be the result of the weirdness of the config.

- The certificate was created for the FQDN, valid CA signed cert
- The FQDN was supplied as a host in the output
- The initial connection was to the broker via the FQDN, so hostname validation passed on the initial connection
- The kafka client then asked the broker for its metadata, which included the address that it was advertised as
- In this case, the "advertised" listener, set in the kafka config, was an ipaddr:port rather than an FQDN:port.  This caused our library `librdkafka` to do another hostname validation against the new address, which failed.
- Is it possible that Sarama just does the hostname validation against the original address?  Or it also possible that it does not process metadata in the same way as `librdkafka` and never even knew about the advertised listener address 🤷‍♂️

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.12.0 BC5 kibana cloud environment and found it **fixed now**.

**Observations:**
- No error for Kafka output is displayed for Elastic Defend on 8.12.0 BC5.
- Elastic Defend data gets populated on Kafka broker.


**Build details:**
VERSION: 8.12.0
BUILD: 70053
COMMIT: db9b8921b37139cbb1e11d23f6381f655edeb72b
Artifact Link: https://staging.elastic.co/8.12.0-9f05a310/downloads/beats/elastic-agent/elastic-agent-8.12.0-windows-x86_64.zip

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/0c307fc3-b86f-4058-a48b-3321ba462df1)


Hence we are **closing** this issue and marking as **QA:Validated**.

Thanks!

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/cases/view/271198

Thanks
