### ISSUE TITLE
[Flaky Test]:  TestContainerCMD –  TempDir RemoveAll cleanup: unlinkat .../data: directory not empty

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#4246]
### Failing test case

TestContainerCMD

### Error message

One of the directories created with t.TempDir() cannot be cleaned up

### Build

https://buildkite.com/elastic/elastic-agent/builds/7054#018d9e30-e528-45a6-b191-402d9e7a6b89

### OS

Linux

### Stacktrace and notes

```markdown
=== RUN   TestContainerCMD
    container_cmd_test.go:70: Creating enrollment API key...
    fixture.go:262: Extracting artifact elastic-agent-8.13.0-SNAPSHOT-linux-x86_64.tar.gz to /tmp/TestContainerCMD148746147/001
    fixture.go:275: Completed extraction of artifact elastic-agent-8.13.0-SNAPSHOT-linux-x86_64.tar.gz to /tmp/TestContainerCMD148746147/001
    fixture.go:865: Components were not modified from the fetched artifact
    container_cmd_test.go:113: >> running binary with: [/tmp/TestContainerCMD148746147/001/elastic-agent-8.13.0-SNAPSHOT-linux-x86_64/elastic-agent container]
    fixture.go:632: >> running binary with: [/tmp/TestContainerCMD148746147/001/elastic-agent-8.13.0-SNAPSHOT-linux-x86_64/elastic-agent status --output json]
    fixture.go:632: >> running binary with: [/tmp/TestContainerCMD148746147/001/elastic-agent-8.13.0-SNAPSHOT-linux-x86_64/elastic-agent status --output json]
    fixture.go:632: >> running binary with: [/tmp/TestContainerCMD148746147/001/elastic-agent-8.13.0-SNAPSHOT-linux-x86_64/elastic-agent status --output json]
    fixture.go:632: >> running binary with: [/tmp/TestContainerCMD148746147/001/elastic-agent-8.13.0-SNAPSHOT-linux-x86_64/elastic-agent status --output json]
    fixture.go:632: >> running binary with: [/tmp/TestContainerCMD148746147/001/elastic-agent-8.13.0-SNAPSHOT-linux-x86_64/elastic-agent status --output json]
    container_cmd_test.go:90: >> cleaning up: killing the Elastic-Agent process
    testing.go:1225: TempDir RemoveAll cleanup: unlinkat /tmp/TestContainerCMD148746147/001/elastic-agent-8.13.0-SNAPSHOT-linux-x86_64/data: directory not empty
--- FAIL: TestContainerCMD (28.62s)

It happened once only on the specific build, still logging it here for tracking
```

**Comment by AndersonQ** [comment]
> It happened once only on the specific build, still logging it here for tracking
￼
it happened on my PR as well: https://buildkite.com/elastic/elastic-agent/builds/7454#018dd49c-2570-483c-b055-2a64a7a20ada

**Comment by rdner** [comment]
Another failure in https://buildkite.com/elastic/elastic-agent/builds/7936#018e667e-1530-4a04-ab27-9e6bc0d60d25

**Comment by rdner** [comment]
Another failure in https://buildkite.com/elastic/elastic-agent/builds/8689#018f4c9e-5f34-422a-9192-4b032de0a4d4

**Comment by cmacknz** [comment]
CC @belimawr 

The test cleanup is in `cmd.Process.Kill`? https://github.com/elastic/elastic-agent/blob/eaf3c4343603e818b5acb5ad1364a718551d9b8c/testing/integration/container_cmd_test.go#L89-L99

The command is started via https://github.com/elastic/elastic-agent/blob/eaf3c4343603e818b5acb5ad1364a718551d9b8c/pkg/testing/fixture.go#L669-L674

Cancelling the context should kill the process and let us stop using the cleanup function, we could also gracefully call `Stop` before the test ends.

I do think the actual problem is that something is still accessing the `STATE_PATH` at the time  when we try to remove the temporary directory, so removing use of `Cleanup` might just change the timing. The work dir is created with `TempDir` here https://github.com/elastic/elastic-agent/blob/eaf3c4343603e818b5acb5ad1364a718551d9b8c/pkg/testing/fixture.go#L208

See https://github.com/golang/go/issues/43547

Possibly the real fix is to poll for the `elastic-agent container` command to have actually stopped when we kill it.

**Comment by cmacknz** [comment]
> What do you mean?

I mean why do we call `cmd.Process.Kill` when cancelling the context does the same thing, but apparently just wrote a bunch of nonsense instead :p

It looks like the `cancel()` in `CommandContext` doesn't `Wait` either, so you nailed it we need to call `Wait()` after calling `Start()` here.

**Comment by belimawr** [comment]
I'l make a quick PR to fix that.

**Comment by belimawr** [comment]
https://github.com/elastic/elastic-agent/pull/4695
