### ISSUE TITLE
Agent `install -f` Leaves Orphaned Tamper-Protected Endpoint

### ISSUE THREAD

**Issue by gabriellandau** [elastic/elastic-agent#4506]
Using `install -f` on top of a tamper-protected Agent/Endpoint replaces Agent but leaves an orphaned Endpoint.

Observed in Agent 8.13.0 on Windows 10 22H2.

### Repro
1. Install Agent 8.11.2
2. Enable Defend integration and Tamper Protection
3. Install Agent 8.13.0 with `install -f`
4. Observe mismatched Agent and Defend versions:
```
C:\>"C:\Program Files\Elastic\Agent\elastic-agent.exe" version
Binary: 8.12.2 (build: de80b0d70174ba45dc869fdf121109763bbfcce0 at 2024-02-19 17:01:34 +0000 UTC)
Daemon: 8.12.2 (build: de80b0d70174ba45dc869fdf121109763bbfcce0 at 2024-02-19 17:01:34 +0000 UTC)

C:\>"C:\Program Files\Elastic\Endpoint\elastic-endpoint.exe" version
version: 8.13.0, compiled: Wed Mar 20 21:00:00 2024, branch: HEAD, commit: f90579240155fc17f659ed37f7864ab1194ed2ea
```

cc @cmacknz

**Comment by cmacknz** [comment]
I suspect this is being caused by the call to `Uninstall` we make if we detect we are installing over a installed agent that is still functional.

https://github.com/elastic/elastic-agent/blob/d6f50353dfd1dd413e810431367c879d93b53959/internal/pkg/agent/install/install.go#L42-L60

The `""` argument in `Uninstall(cfgFile, topPath, "", log, pt)` is the uninstall token, so for a tamper protected agent this can never succeed. This should be failing with a tamper protection error though. I think that's really all we can do here is fail with a tamper protection error and have the user try again by calling `elastic-agent uninstall` with the token.

**Comment by intxgo** [comment]
related to https://github.com/elastic/elastic-agent/issues/4349
