### ISSUE TITLE
Can I customize the "agent.name" when sending data to ES instead of using hostname?

### ISSUE THREAD

**Issue by mumuwithw** [elastic/elastic-agent#4920]
I noticed that the official website provides the following explanation for agent.name:
(At https://www.elastic.co/guide/en/ecs/current/ecs-agent.html )

> Custom name of the agent.
> 
> This is a name that can be given to an agent. This can be helpful if for example two Filebeat instances are running on the same host but a human readable separation is needed on which Filebeat instance data is coming from.
> 
> type: keyword
> 
> example: foo

I want to know how to customize it?

I noticed that someone had a similar question, but there was no effective answer:
- https://discuss.elastic.co/t/how-to-change-an-agent-name-in-elk-8-11/352196
- https://discuss.elastic.co/t/how-to-set-change-elastic-agent-with-same-hostname/354766
- https://discuss.elastic.co/t/elastic-agent-rename-agent-names-or-add-a-field-to-differentiate-them/357491

**Comment by cmacknz** [comment]
You've linked to the ECS documentation, no the Fleet documentation.

You can't customize the agent name in Fleet today beyond opting to use the FQDN or not. It will always be the hostname, but you can have multiple agents with the same hostname managed in Fleet because they are identified by a separate agent ID.
