### ISSUE TITLE
[Flaky Test]: TestRpmLogIngestFleetManaged/Monitoring_logs_are_shipped – failed to evaluate all symlinks

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4929]
### Failing test case

TestRpmLogIngestFleetManaged/Monitoring_logs_are_shipped

### Error message

failed to evaluate all symlinks

### Build

https://buildkite.com/elastic/elastic-agent-extended-testing/builds/625#0190110f-8604-4125-9789-621c5241ef2b

### OS

Linux

### Stacktrace and notes

```markdown
=== RUN   TestRpmLogIngestFleetManaged/Monitoring_logs_are_shipped
    logs_ingestion_test.go:489: Making sure metricbeat logs are populated
    logs_ingestion_test.go:493: metricbeat: Got 300 documents
    logs_ingestion_test.go:498: Making sure all components are healthy
    logs_ingestion_test.go:500: 
        	Error Trace:	/home/rhel/agent/testing/integration/logs_ingestion_test.go:500
        	            				/home/rhel/agent/testing/integration/logs_ingestion_test.go:241
        	Error:      	Received unexpected error:
        	            	could not unmarshal agent status output: error: error creating cmd: failed to get control protcol address: failed to evaluate all symlinks of /tmp/TestRpmLogIngestFleetManaged3099371811/001/elastic-agent-8.15.0-SNAPSHOT-x86_64: lstat /tmp/TestRpmLogIngestFleetManaged3099371811/001/elastic-agent-8.15.0-SNAPSHOT-x86_64: no such file or directory, output: 
        	            	unexpected end of JSON input
        	Test:       	TestRpmLogIngestFleetManaged/Monitoring_logs_are_shipped
        	Messages:   	could not get agent status to verify all components are healthy
--- FAIL: TestRpmLogIngestFleetManaged/Monitoring_logs_are_shipped (15.30s)
```

**Comment by rdner** [comment]
Also happened in:

* https://buildkite.com/elastic/elastic-agent-extended-testing/builds/626#0190110f-ba61-431a-9d55-4fc925cd5600
* https://buildkite.com/elastic/elastic-agent-extended-testing/builds/627#0190110f-b8c4-42ea-8b61-ad907bdf0f08
* https://buildkite.com/elastic/elastic-agent-extended-testing/builds/628#01901110-3058-4208-a2be-c3f1da97bdcc

**Comment by cmacknz** [comment]
The failing line is:

https://github.com/elastic/elastic-agent/blob/e8962b0e4857f1e66d5b4887b4c8fcbb4f1e8af0/pkg/testing/fixture.go#L670-L674

> failed to evaluate all symlinks of /tmp/TestRpmLogIngestFleetManaged3099371811/001/elastic-agent-8.15.0-SNAPSHOT-x86_64: no such file or directory

The DEB and RPM tests are the ones that are failing, and this makes some sense, because they do not use any paths under `/tmp` and that won't be the path to the agent command. For those packages the symlink ends up under `/var/lib`. https://github.com/elastic/elastic-agent/blob/e8962b0e4857f1e66d5b4887b4c8fcbb4f1e8af0/dev-tools/packaging/packages.yml#L66

I think the DEB and RPM install commands are missing setting up a client at the right socket path. I am actually surprised this failure doesn't happen every time more than anything.

Here is the client getting created on the regular install path:

https://github.com/elastic/elastic-agent/blob/e8962b0e4857f1e66d5b4887b4c8fcbb4f1e8af0/pkg/testing/fixture_install.go#L205-L217

Here is the DEB install which does not set this up, so we fall back to trying to find the control socket in work dir, which is a temporary directory.

https://github.com/elastic/elastic-agent/blob/e8962b0e4857f1e66d5b4887b4c8fcbb4f1e8af0/pkg/testing/fixture_install.go#L435

The DEB and RPM install are also missing the clean up calls to get diagnostics and dump processes. https://github.com/elastic/elastic-agent/blob/e8962b0e4857f1e66d5b4887b4c8fcbb4f1e8af0/pkg/testing/fixture_install.go#L251-L254

**Comment by ycombinator** [comment]
Another failure in https://buildkite.com/elastic/elastic-agent-extended-testing/builds/1918#01915121-b869-4cc3-9ab1-fa053f0eb39f

**Comment by rdner** [comment]
@ycombinator the failure you linked seems to be new/unrelated, see https://github.com/elastic/elastic-agent/issues/5311

**Comment by VihasMakwana** [comment]
This test is passing now, thanks to https://github.com/elastic/elastic-agent/pull/4938.
Offending [code](https://github.com/pchila/elastic-agent/blob/472a9910100d6b5a88cc3800fd0c87db6708fea6/pkg/testing/fixture.go#L669-L676). 
Closing this.
