### ISSUE TITLE
[Flaky Test]: TestActionDispatcher/Dispatch_multiples_events_returns_one_error – Expected error

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4937]
### Failing test case

TestActionDispatcher/Dispatch_multiples_events_returns_one_error

### Error message

dispatcher_test.go:393: Expected error

### Build

https://buildkite.com/elastic/elastic-agent/builds/9615#0190110f-0b1c-45ba-81d9-c1406e137e09

### OS

Mac

### Stacktrace and notes

```markdown
=== Failed
=== FAIL: internal/pkg/agent/application/dispatcher TestActionDispatcher/Dispatch_multiples_events_returns_one_error (0.52s)
    dispatcher_test.go:393: Expected error
=== FAIL: internal/pkg/agent/application/dispatcher TestActionDispatcher (1.52s)
```

**Comment by rdner** [comment]
Happens only on Mac, there are multiple occurrences, at least in 2 more builds:

* https://buildkite.com/elastic/elastic-agent/builds/9616#0190110f-a4fa-47fc-adcf-643d5325d414
* https://buildkite.com/elastic/elastic-agent/builds/9624#0190115a-d22e-4136-9723-54bbd5d63c2f

**Comment by rdner** [comment]
Failed again in https://buildkite.com/elastic/elastic-agent/builds/9709#01902a0b-20aa-433d-9a48-dce44c553af2

**Comment by pchila** [comment]
Given the long times for the unit tests run on Mac for the builds where It failed, I guess that the 200 ms sleeps we have are not enough (in a well designed unit test we should not rely on time.Sleep to make things work but it's at least marked as a workaround in code)
https://github.com/elastic/elastic-agent/blob/1a05982eb6acd61850c55098464ed1265d46b7fb/internal/pkg/agent/application/dispatcher/dispatcher_test.go#L384-L400

These should probably replaced by longer timeouts in the `select` statements instead of the `default` case  (even better if we could rely on a global unit test timeout of a few seconds (if we find one that is reliable enough without being too long) and block on the errors channel

**Comment by ycombinator** [comment]
Failed again in https://buildkite.com/elastic/elastic-agent/builds/11012#01914cd9-8183-43ac-8f12-b02a80bfde86
