### ISSUE TITLE
Mount /etc/machine-id in elastic-agent-managed-kubernetes.yaml

### ISSUE THREAD

**Issue by daniel-almeida** [elastic/elastic-agent#512]
**Describe the enhancement:**

Change the yaml for managed Agent in k8s so that it has a volume for `/etc/machine-id` that is mounted in the Agent's container. 

New volume mount for the elastic-agent container:
```
- name: etc-mid
  mountPath: /etc/machine-id
  readOnly: true
```

New volume:
```
- name: etc-mid
  hostPath:
    path: /etc/machine-id
    type: File
```

**Describe a specific use case for the enhancement or feature:**

To determine `host ID`, Agent needs the content of `/etc/machine-id` (see https://github.com/elastic/go-sysinfo/blob/main/providers/linux/machineid.go#L32).

Currently, the file is present in the container, but empty, which results in Agent using the value `""` when determining the host ID, and sending an empty host ID to endpoint. That makes the policy status unhealthy because Endpoint requires a valid host ID.

**Comment by lrishi** [comment]
Cc: @norrietaylor @m-sample @qcorporation

**Comment by m-sample** [comment]
+1 on readOnly! Given that `type: File` means `A file must exist at the given path` we should test of what happens when that file does not exist (e.g. on some mutant, hacked over Linux setup). If it's not a good response (e.g. Pod fails to launch) we may want to document it well for SDH avoidance or perhaps leave the `type` field as unspecified for 'no checks' behavior.

(Pod volume mount `type` field docs: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath )
