### ISSUE TITLE
[Discuss][Meta] Add integration tests to `elastic-agent` repository

### ISSUE THREAD

**Issue by narph** [elastic/elastic-agent#56]
ATM we are depending on the `e2e-testing` for end to end testing, but the tests have been broken several times in the past due to unrelated issues or not having been updated to the latest changes and more than often they turn out to be fragile.
The `e2e tests` should also come with some ownership responsibility when it comes to keeping them up to date or investigating failures and redirecting them to the right team. 

The e2e tests are also not run by default in the new repo, they can be triggered by:
```
anyOf {
          expression { return params.end_to_end_tests_ci }
          expression { return env.GITHUB_COMMENT?.contains('e2e tests') }
          expression { matchesPrLabel(label: 'ci:end-to-end') }
        }
```
or we should decide if we want them run all the time.

That aside, we should consider looking into defining a test plan for integration tests inside the `elastic agent` repo.
The obs-robots team recommended looking into https://github.com/testcontainers/testcontainers-go, several elastic repos are also using this package. 
I quickly evaluated this library but I've ended up almost replicating what the e2e tests has already implemented. I wonder if we should reuse the `e2e testing` more as a library inside the repo.

I am not aware if there are any on-going efforts when it comes to testing (including in the v2 plans) @ruflin , @ph, please confirm here but I think we should start defining testing scenarios and creating integration tests in the new repo.

@jlind23 , @elastic/elastic-agent-control-plane let me know what you all think

**Comment by jlind23** [comment]
I do think we need both tests type.
The e2e testing repository is pretty useful for us to check some "basic" behaviour or the elastic agent on a huge bunch of different operating systems. This is truly needed as we will continue adding more and more OS along the way.

But, those e2e tests shouldn't replace at all the integration tests that we should put in place. Using test containers library definitely seems to be the way to go.

@narph @mdelapenya How much time to we need to set up a first dummy test using test containers library and adding this test as part of our PRs quality gate? As soon as the basic architecture is in place it is going to be much more simpler to add tests on top of it.

**Comment by mdelapenya** [comment]
It would depend on the test of course. I'd suggest defining one simple test, and add the automation to run it in the current build. 

> SPOILER: I'm one of the core maintainers in the library, so it shouldn't be that much :)

But I'd prefere having a clear understanding of what test to write, and then "estimate" how much time it is.

**Comment by jlind23** [comment]
> Starting up the agent container and checking that there is 4 processes running (2metricbeat 2filebeat) seems to be a good start right?

**Comment by joshdover** [comment]
+1 I think integration or functional tests are a missing gap, especially in the context of the v2 architecture. IMO we need to be able to run tests from the elastic-agent repository that can exercise all the expected behavior / touch points with:
- Fleet Server, against a faux/mocked server
  - This should include tests that verify the backoff/retry behaviors
  - Enrollment, and the container command
- Application binaries, incl service applications (Endpoint), scope:
  - Application lifecycle (install, start, stop, uninstall, upgrade)
  - How the "brain" of agent handles applications that aren't responding
  - Configuration/policy changes, incl. API key invalidation
  - This can be done with mocked binary/apps that can be manipulated from test code
- Agent upgrades
  - Emulating failures at different steps of the process (eg. killed due to OOM)
  - Race conditions during the upgrade process (eg. an application upgrading while agent is told to shutdown)
  - Interactions with the artifact backend
- Monitoring

@narph's spacetime work in https://github.com/elastic/elastic-agent/pull/1068 is a great start to getting some basic tests working for enrollment. I'd also like to see what we could do without starting up the entire stack and focusing more on the agent behavior, esp for the application binary management behavior and upgrade behavior which are largely de-coupled from ES and Fleet Server.

@blakerouse I'm curious what has been considered in this realm as part of the v2 work. Do you think these would be valuable enough to have before we merge in the v2 changes to main?
