### ISSUE TITLE
[Helm] Chart does not mount `/var/log/containers/` on Elastic-Agent pod, thus no logs are ingested

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#6204]
- Version: `8.16.0`, `main`, 
- Operating System: Kubernetes

The Helm chart does not mount `/var/log/containers/` into the Elastic-Agent container, therefore it cannot read logs from any container in the cluster.

## Steps to reproduce
1. Add the Kubernetes integration with logs enabled to a new Elastic-Agent policy
2. Follow the steps to install the Helm Chart from [our documentation](https://www.elastic.co/guide/en/fleet/current/example-kubernetes-fleet-managed-agent-helm.html) using the policy created on step 1.
3. There will be no logs ingested from the Kubernetes cluster. You can confirm that by filtering the logs using `event.dataset: kubernetes.container_logs`

## Workaround
Use the manifest provided in Kibana when selecting "Add agent" -> "Kubernetes"

**Comment by pkoutsovasilis** [comment]
thanks for the issue @belimawr, so what happens here is that under fleet mode the chart does nothing that derives from an integration config, as this is controlled by fleet. As a result, this choice leads to volument mounts and other bits, as you already observed, to not be in the k8s manifest of elastic-agent. Specifically in this case the container logs volume mount which is injected when a user selects to enable the kubernetes integration doesn't apply here. Most probably we want to alter this behaviour and allow a user to enable integrations even when deploying a managed by fleet elastic-agent which results in maintaining these bits and not the elastic-agent config

**Comment by pkoutsovasilis** [comment]
> Because the default configuration of the Kubernetes integration is to collect pod logs, I believe we should have the mount enabled by default in the helm chart.

I hear you and you already captured something that is not enabled by default, the Kubernetes integration 🙂 What I mean is that the fact that a user installs a Fleet-managed agent in practice is not tightly coupled with the Kubernetes integration and the volume mount is only needed for the latter. Thus having by default on in the kubernetes integration (which the user can enable by `--set kubernetes.enabled=true` makes total sense)  but having it by default just because a user installs a Fleet-managed agents seems a little bit too aggressive

**Comment by belimawr** [comment]
I see your point, it makes sense.

**Comment by swiatekm** [comment]
In general, it is the case that a user can add integrations in Fleet that their agent deployment in K8s is unable to run, due to missing mounts or permissions. Container logs are just the most obvious example of this, but it applies just as well to system metrics (require a /proc mount from the Node) or cluster metrics (require specific RBAC). In the absence of an actual operator that Fleet could talk to, the best we can do is either:

1. Install agent with a superset of all necessary mounts and permissions, give instructions on how to cut them down if the user wants to.
2. Install agent with only the necessary mounts and permissions, give instructions on how to redeploy the agent if the user adds integrations which require more.

Right now, I think we're going with 2? But it's a valid discussion to have.

**Comment by cmacknz** [comment]
1 is closer to the current strategy in the reference configurations. https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml. This makes sure everything works when getting started and experimenting. The drawback is we get regular requests to explain or reduce the mounts and privilege level to the minimum required for a use case. Often these requests block deployment or adoption of agent until they are resolved.

My current view on this would be that:
1. The Kubernetes integration should be enabled by default, and we should setup whatever we need to read container logs and contact the k8s apiserver by default. There should be options to disable particular capabilities (e.g. removing the container log directory mount if container logs aren't desired) and easily disable Kubernetes monitoring entirely. Disabling k8s monitoring is another very common request for people who want to collect data while running agent on k8s but are monitoring k8s in another way.
2. The system integration should be disabled by default, but when it gets enabled it should have the capabilities and mounts to get the most common metrics. Often when this gets enabled it is to monitor the node (cpu, memory, io, disk, network, etc) and that should work out of the box when the system integration is enabled, but monitoring the node requires doing more to break the container-host boundary.

This would establish that on a native system where agent runs as a service, system is the default integration. When run on Kubernetes, the Kubernetes integration is the default integration because the cluster is the system in this world.

CC @mlunadia in case you have opinions here.

**Comment by danfinn** [comment]
Did anything ever come out of this?  I'm asking as a user who is attempting to get standalone elastic-agent installed and configured using elastic operator and I'm really struggling to find a configuration which ships pod logs.  I can get metrics and I can get the logs from the agents themselves but I've not yet been able to find a config which will work to ship logs from all the other containers running on the k8s cluster and it sure would be nice if this worked out of the box like @cmacknz suggested.

**Comment by pkoutsovasilis** [comment]
@danfinn , could you please give me a link to what you mean by `elastic operator`? So this issue was about the helm chart and fleet-managed agents, but you are referring to a standalone one. If you deploy a standalone elastic-agent using the elastic-agent helm by default it has kubernetes integration enabled that ships logs. Did you try this and it didn't work for you? 🙂

**Comment by danfinn** [comment]
Sorry, to clarify I'm trying to use ECK to deploy elastic-agents which I assume would use the same config as the helm chart

I've tried using the examples here but they do not work for me and you will also notice that they do not mention logs but only metrics and the configs are also only setup to ship metrics:
https://www.elastic.co/docs/deploy-manage/deploy/cloud-on-k8s/configuration-examples-standalone

**Comment by pkoutsovasilis** [comment]
Ah, now I see — you’re using the cloud-on-k8s Helm chart. However, this issue is about the dedicated elastic-agent Helm chart, which, by the way, supports ECK 🙂.

Since you’ve already installed the ECK operator, you can follow [this example](https://github.com/elastic/elastic-agent/tree/main/deploy/helm/elastic-agent/examples/eck) to deploy a standalone Elastic Agent that uses ECK but leverages our team’s Helm chart.

Note: The instructions in the example are tailored for the chart in the repo, but our team’s chart is already published, so you can install it like this:
```
helm repo add elastic https://helm.elastic.co/
helm install elastic-agent elastic/elastic-agent \
  -n kube-system \
  --set agent.engine=eck \
  --set outputs.default.type=ESECKRef \
  --set outputs.default.name=your-es-name
```

You can also list all available versions of our chart (which are tightly coupled to the Elastic Agent versions) with:
```
helm search repo elastic/elastic-agent --versions
```

**Comment by danfinn** [comment]
I'm a little confused by this.  Why would I install elastic-agent via helm chart when I could be installing it using the ECK operator?  Isn't that the point of the operator?  I will try this as I'm curious if I install via the helm chart if it ships logs by default but I think if I'm using ECK I should also be using the operator for the agent?

**Comment by pkoutsovasilis** [comment]
ECK operator is indeed responsible for managing the lifecycle of Elastic resources, including Agent CRDs. However, when using our dedicated elastic-agent Helm chart with `agent.engine=eck`, Helm doesn’t install the Elastic Agent directly — instead, it generates and applies the necessary configuration (including the Agent CRD) that ECK will reconcile. 

So in this case, the Helm chart is just a convenience to scaffold the correct Agent config for you — including bsupport for k8s logs, metrics, etc. That said, if you prefer to manage the Agent CRDs manually, you could use helm template to generate the YAML and inspect or modify it before applying:

```
helm template elastic-agent elastic/elastic-agent \
  --set agent.engine=eck \
  --set outputs.default.type=ESECKRef \
  --set outputs.default.name=your-es-name
```

So ultimately, it’s up to you — use Helm for a quick start or just as a config generator and then apply through your preferred workflow 👍

**Comment by danfinn** [comment]
Ah, this is perfect, thanks much!  And I can confirm that I am now getting logs form other pods running on the k8s cluster using the helm chart install for elastic-agent so I will now try to backtrack and get the working config from the helm chart and try to deploy that with the operator which I think I prefer to use if I can get it working.

I will say that as a user, the documentation around all of this could definitely be improved and it would also be nice if the elastic-agent installed via the operator worked out of the box.  Thanks much for your help in clarifying this!
